### ISSUE TITLE
removing unused extract loaded assets bug

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#255]
Removing multiple extract loaded assets often removes a large amount of unused assets that weren't selected.

Because of this on reloading the map will show almost all extract loaded assets have been removed in the assets menu (a lot of red)

**Comment by RexTheWho** [comment]
update, Issue seems to mainly be extract loading misses out on adding .units to the add.xml
I suggest adding a warning in the assets menu for missing .units and .object in a loaded asset since those 2 are mandatory

**Comment by RexTheWho** [comment]
Update, been using extract loading more now.
Clicking "unload asset" while lots of other unused assets are shown will cause all or most of those unused assets to be removed, this also includes things like cubemap textures.

**Comment by Luffyyy** [comment]
Remake issue if relevant
