### ISSUE TITLE
the "fled" event in EnemyDummyTrigger does not work when spawnenemydummy units are managed

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/BeardLib-Editor#263]
tested to see if a civilian exiting the map via fleepoint would trigger my "debug_civ_fled" element but it doesn't even trigger it. even if you make it so your enemydummytrigger is set up to execute a debug element which would basically tell you "hey, a civilian fled because i was executed because a civilian left the level via a fleepoint" the debug trigger isn't executed.

**Comment by Whurrhurr** [comment]
found out what the problem was. if you copy and paste an enemydummytrigger element and change the event to "fled" nothing will happen when a managed unit flees.

**Comment by RexTheWho** [comment]
Able to explain what the objective is here? Ill take a shot at getting it to work and see what might be wrong.

**Comment by Whurrhurr** [comment]
my objective is trying to add a special spawn loop to undercover, the only problem is that i need 3 (well 2 technically) enemydummytriggers: 1 for when they spawn 1 for when they die and 1 for when they flee, dummytriggers 2 and 3 increment a counter which is executed when it reaches 2 which executes a counteroperator to reset the counter back to 0 and executes a random element to decide which special pair to spawn next. but because the "fled" event doesn't work with managed SpawnEnemyDummy elements if one of the specials flee the entire thing breaks.

**Comment by RexTheWho** [comment]
Fled only applies to Civilian Ai, Enemies despawning dont seem to have a trigger. Scripted stuff like security leaving would likely have an SO trigger say when they get somewhere and vanish with an AiRemove element.

**Comment by Luffyyy** [comment]
guess closing it with what Rex said.
