### ISSUE TITLE
[Saving, Environments] Saving will occasionally duplicate certain environment units

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#275]
Reproduction steps are unknown, all I know if saving can cause this enough that it turned my 9 sound environment units to 54 while all being on top of each other.

Example video showing the aftermath of this issue over time: https://puu.sh/BBEme/a6079d6b2b.mp4

**Comment by ontrigger** [comment]
This could be caused by alt-dragging

**Comment by RexTheWho** [comment]
The video certainly isnt alt-dragging. If you alt drag those units they get deselected and you dont move them until you select them again.

**Comment by Luffyyy** [comment]
Really weird considering world.world is generic xml not custom xml

**Comment by Luffyyy** [comment]
I need confirmation whether this still happens.

**Comment by RexTheWho** [comment]
Havent seen it happen in a while, but I havent been testing any levels that have environments so no idea if its fixed yet.

**Comment by Luffyyy** [comment]
Oops

**Comment by Luffyyy** [comment]
Remake issue if happens again
