### ISSUE TITLE
[Element] AiAttention element is incomplete

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#311]
AiAttention is incomplete, They require an attention object/unit to be linked. The 
`<entry key="att_obj_u_id" type="number" value="100000"/>`

EDIT:
Additionally, opening Manage Instigator IDs without applying an element will cause the AiAttention element to fail due to a blank list being left behind.

**Comment by Luffyyy** [comment]
Until Znix makes some function so we can read files inside the game without the need of extract I'll probably not bother with this.

**Comment by ontrigger** [comment]
fixed the element breaking if no instigator id is selected
