### ISSUE TITLE
[Bug/UI] some selected units will not display any unit path at all

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/BeardLib-Editor#362]
![218620_20190614165845_1](https://user-images.githubusercontent.com/33162051/59544483-c1f15c00-8ec6-11e9-93a5-7391c4191d0f.png)
some units when you select them will not show anything in the unit path in the selection menu, other units will show the unit path just fine.

**Comment by Luffyyy** [comment]
Oddly doesn't happen for me. Tried updating BeardLib?

**Comment by Whurrhurr** [comment]
updated beardlib, still having this issue.
