### ISSUE TITLE
Access violation when attempting to spawn/change an existing unit to a different unit

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/BeardLib-Editor#369]
Script stack:
            update_positions()  @mods/BeardLib-Editor-master/Classes/Map/StaticEditor.lua:310  
                   set_units()  @mods/BeardLib-Editor-master/Classes/Map/StaticEditor.lua:127  
              mouse_released()  @mods/BeardLib-Editor-master/Classes/Map/StaticEditor.lua:110  
               mouse_release()  @mods/BeardLib-Editor-master/Classes/MapEditor.lua:269  
               mouse_release()  392                                                 
                                lib/managers/mousepointermanager.lua:351            

repro steps: either use spawning mode and press LMB a bunch until you (eventually) crash or change a unit to a different unit until you crash.

**Comment by Luffyyy** [comment]
Doesn't seem to happen

**Comment by Whurrhurr** [comment]
seems to be some stupid "one in a million chance that fixes itself for no reason at all when you update/reinstall the editor" issue, closing issue.
