### ISSUE TITLE
[UI] Heavy lag when selecting instances (Input/Output Events)

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#370]
If you have many instances in a level a noticeable drop in frames happens when selecting them.
It gets even worse the more instances you select for the InstanceInputEvent element.

**Comment by Luffyyy** [comment]
Could you send a map that has that issue?

**Comment by RexTheWho** [comment]
Cant send a copy atm but so far it seems to only be an issue with custom instances.

**Comment by Luffyyy** [comment]
After almost 2 years I cannot confirm this issue. I've played around, spawned a bunch of custom instances (hundreds of them) and I haven't seen "heavy" lag so I'm closing it. If anyone has that issue, please open a new issue with a map for me to test this.
