### ISSUE TITLE
Can't load any level in editor

### ISSUE THREAD

**Issue by StudyWolf-tech** [Luffyyy/BeardLib-Editor#371]
When I try to load any level in the editor, it would crash after initializing World Definition. The thing that bothers me is that it worked before, and when I restarted my pc, it started to do this. The crash log states

```
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     ???                                                 


-------------------------------

Current thread: FileStreamer

-------------------------------
```

**Comment by Luffyyy** [comment]
Send me your BLT log (found in mods/logs a text file with a date as a name)
Additionally, what OS are you running on?

**Comment by StudyWolf-tech** [comment]
I am on windows 10, I re did the problem and got this, 


01:09:01 PM Log:  (c:\users\znix\source\repos\superblt\src\debug\blt_debug.cpp:124) Command line: "C:\Program Files (x86)\Steam\steamapps\common\PAYDAY 2\payday2_win32_release.exe"
01:09:01 PM Log:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:255) Scanning for signatures in payday2_win32_release.exe
01:09:01 PM Log:  (c:\users\znix\source\repos\superblt\platforms\w32\signatures\signatures.cpp:301) Scanned for 48 signatures in 15 milliseconds with 0 cache misses
01:09:01 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:847) Initiating Hook
01:09:04 PM Log:  (c:\users\znix\source\repos\superblt\src\tweaker\wrenloader.cpp:29) [WREN] XML-Tweaking Bundle File 4c0050abde43d6e0.6814330b36ac32f7
01:09:06 PM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:51) CURL_INITD
01:09:06 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:847) Initiating Hook
01:09:06 PM Lua: [BLT] Setup...
01:09:06 PM Lua: [BLT] Loading module: 	BLTLogs
01:09:06 PM Lua: [BLT] Loading module: 	BLTModManager
01:09:06 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
01:09:06 PM Lua: [BLT] Loading module: 	BLTPersistScripts
01:09:06 PM Lua: [BLT] Loading module: 	BLTLocalization
01:09:06 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
01:09:06 PM Lua: [BLT] Loading mods for state: table: 0x001c8980
01:09:06 PM Lua: [BLT] Loading mod: base
01:09:06 PM Lua: [BLT] Loading mod: BeardLib
01:09:06 PM Lua: [BLT] Loading mod: BeardLib-Editor-master
01:09:06 PM Lua: [BLT] Setting up mod: 	base
01:09:06 PM Lua: [BLT] Setting up mod: 	BeardLib
01:09:06 PM Lua: [BLT] Setting up mod: 	BeardLib-Editor-master
01:09:06 PM Lua: [BLT] Loading native module for BeardLib-Editor-master
01:09:06 PM Log:  (c:\users\znix\source\repos\superblt\src\plugins\plugins.cpp:34) Loading binary extension mods/BeardLib-Editor-master/Tools/blep.dll
01:09:06 PM Lua: [BLT] Loading native module for BeardLib-Editor-master
01:09:06 PM Log:  (c:\users\znix\source\repos\superblt\src\plugins\plugins.cpp:34) Loading binary extension mods/BeardLib-Editor-master/Tools/lfs_sblt.dll
01:09:06 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:847) Initiating Hook
01:09:06 PM Lua: [BLT] Setup...
01:09:06 PM Lua: [BLT] Loading module: 	BLTLogs
01:09:06 PM Lua: [BLT] Loading module: 	BLTModManager
01:09:06 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
01:09:06 PM Lua: [BLT] Loading module: 	BLTPersistScripts
01:09:06 PM Lua: [BLT] Loading module: 	BLTLocalization
01:09:06 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
01:09:06 PM Lua: [BLT] Loading mods for state: table: 0x001c8960
01:09:06 PM Lua: [BLT] Loading mod: base
01:09:06 PM Lua: [BLT] Loading mod: BeardLib
01:09:06 PM Lua: [BLT] Loading mod: BeardLib-Editor-master
01:09:06 PM Lua: [BLT] Setting up mod: 	base
01:09:06 PM Lua: [BLT] Setting up mod: 	BeardLib
01:09:06 PM Lua: [BLT] Setting up mod: 	BeardLib-Editor-master
01:09:06 PM Lua: [BLT] Loading native module for BeardLib-Editor-master
01:09:06 PM Lua: [BLT] Loading native module for BeardLib-Editor-master
01:09:07 PM Lua: [BeardLib] [Base Framework] Initialized Mod: mods/BeardLib-Editor-master/
01:09:07 PM Lua: [BeardLib] [Map Framework] Could not read Maps/backups/main.xml
01:09:07 PM Lua: [BeardLib] [Map Framework] Initialized Mod: Maps/NiceHeist/
01:09:07 PM Lua: [BeardLib] [Map Framework] Initialized Mod: Maps/The GenZ Bank/
01:09:07 PM Lua: Loading mod settings : nil
01:09:08 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:847) Initiating Hook
01:09:08 PM Lua: [BLT] Setup...
01:09:08 PM Lua: [BLT] Loading module: 	BLTLogs
01:09:08 PM Lua: [BLT] Loading module: 	BLTModManager
01:09:08 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
01:09:08 PM Lua: [BLT] Loading module: 	BLTPersistScripts
01:09:08 PM Lua: [BLT] Loading module: 	BLTLocalization
01:09:08 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
01:09:08 PM Lua: [BLT] Loading mods for state: table: 0x25932c20
01:09:08 PM Lua: [BLT] Loading mod: base
01:09:08 PM Lua: [BLT] Loading mod: BeardLib
01:09:08 PM Lua: [BLT] Loading mod: BeardLib-Editor-master
01:09:08 PM Lua: [BLT] Setting up mod: 	base
01:09:08 PM Lua: [BLT] Setting up mod: 	BeardLib
01:09:08 PM Lua: [BLT] Setting up mod: 	BeardLib-Editor-master
01:09:08 PM Lua: [BLT] Loading native module for BeardLib-Editor-master
01:09:08 PM Lua: [BLT] Loading native module for BeardLib-Editor-master
01:09:11 PM Lua: [BeardLib-Editor] Loading DBPaths
01:09:12 PM Lua: [BeardLib-Editor] Successfully loaded DBPaths, It took 1.17 seconds
01:09:31 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
01:09:31 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) https://api.modwork.shop/api.php?command=CompareVersion&did=14924&vid=3.34&token=Je3KeUETqqym6V8b5T7nFdudz74yWXgU - 9273
01:09:31 PM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
01:09:32 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
01:09:32 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) https://znix.xyz/paydaymods/updates/meta.php?id=payday2blt - 25130
01:09:32 PM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
01:09:32 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:418) Incoming HTTP Request/Request
01:09:32 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:432) https://znix.xyz/paydaymods/updates/meta.php?id=payday2bltwsockdll - 25127
01:09:32 PM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:168) Launching Async HTTP Thread
01:09:46 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:847) Initiating Hook
01:09:46 PM Lua: [BLT] Setup...
01:09:46 PM Lua: [BLT] Loading module: 	BLTLogs
01:09:46 PM Lua: [BLT] Loading module: 	BLTModManager
01:09:46 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
01:09:46 PM Lua: [BLT] Loading module: 	BLTPersistScripts
01:09:46 PM Lua: [BLT] Loading module: 	BLTLocalization
01:09:46 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
01:09:46 PM Lua: [BLT] Loading mods for state: table: 0x33960ae0
01:09:46 PM Lua: [BLT] Loading mod: base
01:09:46 PM Lua: [BLT] Loading mod: BeardLib
01:09:46 PM Lua: [BLT] Loading mod: BeardLib-Editor-master
01:09:46 PM Lua: [BLT] Setting up mod: 	base
01:09:46 PM Lua: [BLT] Setting up mod: 	BeardLib
01:09:46 PM Lua: [BLT] Setting up mod: 	BeardLib-Editor-master
01:09:46 PM Lua: [BLT] Loading native module for BeardLib-Editor-master
01:09:46 PM Lua: [BLT] Loading native module for BeardLib-Editor-master
01:09:47 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:847) Initiating Hook
01:09:47 PM Lua: [BLT] Setup...
01:09:47 PM Lua: [BLT] Loading module: 	BLTLogs
01:09:47 PM Lua: [BLT] Loading module: 	BLTModManager
01:09:47 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
01:09:47 PM Lua: [BLT] Loading module: 	BLTPersistScripts
01:09:47 PM Lua: [BLT] Loading module: 	BLTLocalization
01:09:47 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
01:09:47 PM Lua: [BLT] Loading mods for state: table: 0x25501a60
01:09:47 PM Lua: [BLT] Loading mod: base
01:09:47 PM Lua: [BLT] Loading mod: BeardLib
01:09:47 PM Lua: [BLT] Loading mod: BeardLib-Editor-master
01:09:47 PM Lua: [BLT] Setting up mod: 	base
01:09:47 PM Lua: [BLT] Setting up mod: 	BeardLib
01:09:47 PM Lua: [BLT] Setting up mod: 	BeardLib-Editor-master
01:09:47 PM Lua: [BLT] Loading native module for BeardLib-Editor-master
01:09:47 PM Lua: [BLT] Loading native module for BeardLib-Editor-master
01:09:48 PM Log:  (c:\users\znix\source\repos\superblt\src\initiatestate.cpp:847) Initiating Hook
01:09:48 PM Lua: [BLT] Setup...
01:09:48 PM Lua: [BLT] Loading module: 	BLTLogs
01:09:48 PM Lua: [BLT] Loading module: 	BLTModManager
01:09:48 PM Lua: [BLT] Loading module: 	BLTKeybindsManager
01:09:48 PM Lua: [BLT] Loading module: 	BLTPersistScripts
01:09:48 PM Lua: [BLT] Loading module: 	BLTLocalization
01:09:48 PM Lua: [BLT] Cleaning logs folder, lifetime 1 day(s)
01:09:48 PM Lua: [BLT] Loading mods for state: table: 0x37fd0800
01:09:48 PM Lua: [BLT] Loading mod: base
01:09:48 PM Lua: [BLT] Loading mod: BeardLib
01:09:48 PM Lua: [BLT] Loading mod: BeardLib-Editor-master
01:09:48 PM Lua: [BLT] Setting up mod: 	base
01:09:48 PM Lua: [BLT] Setting up mod: 	BeardLib
01:09:48 PM Lua: [BLT] Setting up mod: 	BeardLib-Editor-master
01:09:48 PM Lua: [BLT] Loading native module for BeardLib-Editor-master
01:09:48 PM Lua: [BLT] Loading native module for BeardLib-Editor-master
01:09:49 PM Lua: [BeardLib] [Base Framework] Initialized Mod: mods/BeardLib-Editor-master/
01:09:49 PM Lua: [BeardLib] [Map Framework] Could not read Maps/backups/main.xml
01:09:49 PM Lua: [BeardLib] [Map Framework] Initialized Mod: Maps/NiceHeist/
01:09:49 PM Lua: [BeardLib] [Map Framework] Initialized Mod: Maps/The GenZ Bank/
01:09:49 PM Lua: Loading mod settings : nil
01:09:51 PM Lua: [BeardLib-Editor] Loading DBPaths
01:09:51 PM Lua: [BeardLib-Editor] DBPaths already loaded
01:09:52 PM Lua: [BeardLib-Editor] Loading Custom Assets to Hashlist
01:11:08 PM Log:  (c:\users\znix\source\repos\superblt\src\http\http.cpp:57) CURL CLOSED

**Comment by Luffyyy** [comment]
Not much I can do other than recommending to do some things:
Update BeardLib to latest version (through github)
Trying older commits of the editor and telling me if they work.

**Comment by StudyWolf-tech** [comment]
I tried both of your recommendations, but I finally fixed it after reinstall super BLT!

**Comment by Luffyyy** [comment]
Oh right SBLT had a bad update once. Though I recall I fixed it in BeardLib.
