### ISSUE TITLE
My game crashes

### ISSUE THREAD

**Issue by AndreyPrima** [Luffyyy/BeardLib-Editor#373]
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
              ReadScriptData()  @mods/BeardLib/Classes/Utils/FileIO.lua:77          
                LoadHashlist()  @mods/BeardLib-Editor-master/Core.lua:200           
                        func()  @mods/BeardLib-Editor-master/Core.lua:69            
                        Call()  @mods/base/req/core/Hooks.lua:109                   
          _base_process_menu()  @mods/base/lua/MenuManager.lua:99                   
                                @mods/base/lua/MenuManager.lua:69                   
                       pcall()                                                      
                          =[C]  func()                                              
                                @mods/base/lua/MenuManager.lua:46                   
                        Call()                                                      
@mods/base/req/core/Hooks.lua:109  init()                                              
                                @mods/base/lua/MenuManager.lua:11                   
                         new()                                                      
core/lib/utils/coreclass.lua:35  original()                                          
                                lib/setups/setup.lua:378                            
                    original()                                                      
@mods/base/req/core/Hooks.lua:260  init_managers()                                     
                                @mods/base/req/core/Hooks.lua:185                   
               init_managers()                                                      
  lib/setups/menusetup.lua:273  core/lib/setups/coresetup.lua:382                   

-------------------------------

System information:
	Application version : 1.92.790.
	CPU : Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz (2 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce 940MX / nvldumd.dll[23.21.13.8857]
	Language : russian
	Memory :     8058MB 308KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Динамики (Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
Read the install instructions!
#372
