### ISSUE TITLE
Project/Level UI Editor does not have "player_sequence" property

### ISSUE THREAD

**Issue by FromDarkHell** [Luffyyy/BeardLib-Editor#374]
Specific heists like `Green Bridge`, `Diamond Heist` and Shacklethorne have a property of `player_sequence` that allows the level to modify how the player's clothing is.
When you edit a heist's `main.xml` file and add the `player_sequence` property into the `level` object, it loads just fine. All it needs is a UI option that notes the types of `player_sequence` which are:

- `spawn_prop_winter_suit`
- `spawn_prop_raincoat`
- `spawn_prop_sneak_suit`
- `spawn_prop_tux`
- `spawn_prop_murky_suit`

Edit: Oops forgot some `player_sequence`'s

**Comment by Luffyyy** [comment]
Changed to 'player_style'

**Comment by Luffyyy** [comment]
Added, but you'll have to be careful with them, atm BeardLib/editor don't assist you with the packages for the suits and you'll crash if you won't add them.
