### ISSUE TITLE
[Element] ElementMusic is incomplete

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#375]
Element Music is used in Shadow Raid to change the sound track.

UI says there's no song selected but this is what goes into the missions custom_xml on shadowraid.
`<entry key="music_event" type="string" value="suspense_4"/>`

**Comment by Luffyyy** [comment]
Changed to a simple textbox as the original tries to get events which is not possible in the public version of the game afaik.
