### ISSUE TITLE
[Bug] selecting a sequence on a unit that'd change the color/material_config of the unit sets it to the default material_config defined in the unit's object file

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/BeardLib-Editor#377]
![218620_20190701115954_1](https://user-images.githubusercontent.com/33162051/60460197-f3249880-9bf7-11e9-94e3-daeb13be2316.png)
if a unit was using something other than the default material_config when you do this it will also be set back to the default material_config.

**Comment by mwSora** [comment]
can confirm, though it actually change the sequence after a save + restart

**Comment by Whurrhurr** [comment]
this issue has been fixed (for like over a week now and i only just now got around to doing this) closing issue.
