### ISSUE TITLE
click anything cause crash

### ISSUE THREAD

**Issue by newcomer953** [Luffyyy/BeardLib-Editor#380]
Click on Instances on the Select section when in a level edit cause crash
Crashlog:
Wed Jul 03 17:31:55 2019

Application has crashed: C++ exception
...-Editor-master/Classes/Dialogs/MultiSelectListDialog.lua:125: attempt to compare nil with number

        return true
    end
    local match

SCRIPT STACK

_Show() 121
_Show() @mods/BeardLib-Editor-master/Classes/Dialogs/MultiSelectListDialog.lua:6
update() 141
func() @mods/BeardLib/Core.lua:153
Call() @mods/base/req/core/Hooks.lua:109
update() @mods/base/lua/GameSetup.lua:6
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:540

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

**Comment by Luffyyy** [comment]
At the moment you need to download the latest BeardLib version from GitHub not MWS as the code there gets often updated.
