### ISSUE TITLE
[Bug] Sequences for most models don't visualize until after level is reloaded

### ISSUE THREAD

**Issue by GHBDougley** [Luffyyy/BeardLib-Editor#385]
Title.

For most models (cars, anything that involves a material swap seemingly?) don't work correctly in the editor anymore, and in order to see the changes the sequence makes, you need to save & reload your level.

Can this be fixed where one can see the changed sequence ASAP?  I'm not sure if this is actually intentional behaviour or not.

**Comment by Luffyyy** [comment]
You mean mesh variation? That works fine.

**Comment by RexTheWho** [comment]
Yes, but he means units that have material_config sequences to change their materials reset to default when you try to trigger that sequence in editor.

For example, if you select the Reinforced door present on most levels and choose the black material it stays white until you reload the level. Furthermore if you select the door once its made black it resets to default.

**Comment by GHBDougley** [comment]
^^^

This wasn't happening before -- did a change w/ material variation cause this?

**Comment by Luffyyy** [comment]
> 
> 
> ^^^
> 
> This wasn't happening before -- did a change w/ material variation cause this?

Most likely.
