### ISSUE TITLE
[Environments] Cubemap and Dome Occlusion produces empty textures

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#388]
When baking Cubemaps and Dome Occlusion both produce a blank texture file.
Cubemap a 0 alpha, white 6 sided texture.
Dome occlusion a pitch black image.

**Comment by ontrigger** [comment]
does that still happen?

**Comment by ontrigger** [comment]
dome occ should no longer do that

**Comment by ontrigger** [comment]
everything seems to work now
