### ISSUE TITLE
[ElementBLCustomAchievement] Crashes the game when triggert

### ISSUE THREAD

**Issue by Booo3** [Luffyyy/BeardLib-Editor#395]
Application has crashed: C++ exception
[string "--mods/BeardLib/Classes/CustomAchievementMana..."]:459: attempt to perform arithmetic on local 'amt' (a nil value)

SCRIPT STACK

on_executed() @mods/BeardLib/Classes/Elements/ElementBLCustomAchievement.lua:69
execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:209
_trigger_execute_on_executed() core/lib/managers/mission/coremissionscriptelement.lua:147
on_executed() core/lib/managers/mission/coremissionscriptelement.lua:131
on_executed() lib/managers/mission/missionscriptelement.lua:18
on_executed() core/lib/managers/mission/coreelementarea.lua:121
_check_amount() core/lib/managers/mission/coreelementarea.lua:270
f() core/lib/managers/mission/coreelementarea.lua:235
update() core/lib/utils/coreevent.lua:158
update() core/lib/managers/mission/coremissionmanager.lua:529
update() core/lib/managers/mission/coremissionmanager.lua:160
core/lib/setups/coresetup.lua:503

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name

**Comment by Luffyyy** [comment]
Fixed
