### ISSUE TITLE
[Bug] Editor.. fails to initialize on latest commit?

### ISSUE THREAD

**Issue by GHBDougley** [Luffyyy/BeardLib-Editor#396]
07:15:47 PM Lua: [BeardLib] [Base Framework] [ERROR] An error occured on initilization of mod BeardLib-Editor-master. Error:
nil

This seems to be happening after the latest commit(s) within the past 24 hours.  Unsure why it's failing to initialize.

**Comment by Luffyyy** [comment]
Use latest commit of BeardLib
