### ISSUE TITLE
[Request] Selected to raycast position

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#397]
For workflow reasons something that lets you reposition a unit or element to wherever you click in the world would be useful.

People could copy lots of the same money pile and then just click where they want it to be without having to carefully position it to make it sit on a desk.

**Comment by Luffyyy** [comment]
Like spawning but repositioning?

**Comment by RexTheWho** [comment]
Yes, exactly that.

**Comment by Luffyyy** [comment]
Implemented, it should work with multiple units too. Additionall, you can trigger it using middle mouse button.
