### ISSUE TITLE
[Elements] Some elements remain invisible in vanilla maps

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#398]
When loading vanilla maps elements (usually ones far off the map) are invisible in 3D space, You can still select them from the select elements menu.

Example, in 'branchbank' element ID 105169 is invisible when loading the level in editor.

**Comment by Luffyyy** [comment]
Apparently this happens to elements that have no position (we randomize the poisition then instead so they don't stack up in 0 0 0) I will enable them for now

**Comment by Luffyyy** [comment]
A smart way to deal with it in the future would be to get a random linked element/unit and position it near it.
