### ISSUE TITLE
[Assets] Beardlib Editor loads assets not in Beardlib

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#401]
This is an issue I believe, since its difficult to figure out what unit from the editor is loaded if you crash without it installed.

You cant check what unit it is either since only the editor has the safemode loading.

IIRC one unit that often messes me up often is the cubemap gizmo unit.

**Comment by Luffyyy** [comment]
what

**Comment by RexTheWho** [comment]
Beardlibs editor loads certain assets that sometimes end up in non-editor only continents. This causes crashes.

**Comment by Luffyyy** [comment]
You mean it let's you spawn units that shouldn't be spawned?

**Comment by RexTheWho** [comment]
Not exactly, for example if I leave a cubemap gizmo unit in a level (in a continent that is not editor only) and then try to play the level without the editor installed I crash.
Because Beardlib Editor loads the cubemap gizmo unit not the level itself.

**Comment by Luffyyy** [comment]
Odd that shouldn't spawn, same as nav surfaces

**Comment by RexTheWho** [comment]
Nav surfaces are spawned from the world. cubemap gizmos are a continent unit afaik. It doesnt spawn the same.

**Comment by Luffyyy** [comment]
They should spawn from world iirc

**Comment by RexTheWho** [comment]
Checked, Cubemap Gizmo is a continent unit.
![20190724141927_1](https://user-images.githubusercontent.com/26837908/61769789-0fde7580-ae1e-11e9-8eff-7da21d0ac944.jpg)

Nav Surface is not.
![20190724141957_1](https://user-images.githubusercontent.com/26837908/61769804-1ff65500-ae1e-11e9-9f45-2c5eed4f121d.jpg)
