### ISSUE TITLE
BeardLib - Editor dosen't show up in option

### ISSUE THREAD

**Issue by Mediss0** [Luffyyy/BeardLib-Editor#410]
I ve installed everything correctly and with the newest updates, but i dont have beardlib - editor in options. What can i do now?

**Comment by kakeshka** [comment]
i have this problem too (((

**Comment by Luffyyy** [comment]
did you install it using the instructions? Did you install the data?

**Comment by Blake-HUI** [comment]
Me too, I install all the thing even data.

**Comment by raiSe152** [comment]
me too

**Comment by Luffyyy** [comment]
Install the GitHub version of BeardLib https://github.com/simon-wh/PAYDAY-2-BeardLib
Since the editor usually uses the last features that are not released yet.

**Comment by raiSe152** [comment]
i have github version

**Comment by raiSe152** [comment]
but still there isnt an option for editor

**Comment by Luffyyy** [comment]
I use that too and it shows up no problem. Perhaps send your BLT log (mods/logs)

**Comment by raiSe152** [comment]
[Uploading 2019_08_13_log.txt…]()
[Uploading 2019_08_14_log.txt…]()

**Comment by raiSe152** [comment]
[logs.zip](https://github.com/Luffyyy/BeardLib-Editor/files/3501291/logs.zip)

**Comment by Luffyyy** [comment]
Seems outdated. Download again https://github.com/simon-wh/PAYDAY-2-BeardLib
If it still doesn't work upload your log again (I only need the text file with today's date)

**Comment by raiSe152** [comment]
it worked but it says theres an update for the beardlib like the first time

**Comment by raiSe152** [comment]
i think it doesnt show up if you do that update

**Comment by raiSe152** [comment]
when i go to create project i cant type

**Comment by raiSe152** [comment]
luffy i cant type in creating project

**Comment by Luffyyy** [comment]
Ignore the update. You can disable the notification in the options of BeardLib. Stop reporting other issues here.

**Comment by Luffyyy** [comment]
Also again, works fine for me. You'll have to provide extra info like screenshot, blt log in the issue report.
