### ISSUE TITLE
Cant create a project

### ISSUE THREAD

**Issue by raiSe152** [Luffyyy/BeardLib-Editor#412]
when i try to create a project i cant type its name and when i go back from beardlib menu or beardlib editor menu i cant click anywhere

**Comment by Luffyyy** [comment]
> works fine for me
> You'll have to provide extra info like screenshot, blt log in the issue report.

**Comment by raiSe152** [comment]
i cant type in here
![Screenshot_10](https://user-images.githubusercontent.com/44704050/63091286-904c4e00-bf66-11e9-9e0c-f1bc5de13396.png)

after backing out i cant click anywhere 
![Screenshot_11](https://user-images.githubusercontent.com/44704050/63091325-af4ae000-bf66-11e9-9ddd-7bb925f14eef.png)

**Comment by Luffyyy** [comment]
You didn't give me all that I need

**Comment by raiSe152** [comment]
what do you need

**Comment by raiSe152** [comment]
[2019_08_15_log.txt](https://github.com/Luffyyy/BeardLib-Editor/files/3505609/2019_08_15_log.txt)

**Comment by Luffyyy** [comment]
Odd no idea what's going on

**Comment by raiSe152** [comment]
well fuck

**Comment by raiSe152** [comment]
thanks tho

**Comment by raiSe152** [comment]
is there way to create a project without going there

**Comment by Luffyyy** [comment]
Remove all mods and see if that works

**Comment by raiSe152** [comment]
tried it didnt work

**Comment by raiSe152** [comment]
with or without the mods same

**Comment by Luffyyy** [comment]
Gonna close for now, not sure what is the issue as much.
