### ISSUE TITLE
[Bug] removing units inside the Assets menu does not remove all of the selected unit

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/BeardLib-Editor#413]
if you select "Remove" on a selected asset inside the Assets menu, it asks you if you want to delete it, selecting "Yes" will cause it to remove "All units that are spawned except for those spawned by an instance" the problem is if your level has no instances it still won't delete all of the units of that selected asset. (only seems to be anywhere between 20% to 80% of all units that are spawned by selected asset)

it took me 4 reloads of the my level to remove an unloaded asset that had 10 units (10 units of the unloaded asset existed, after the first reload there were 5, after the second 2, after the third there was only 1 left. after that the unloaded asset was _finally_ removed from my level.)

**Comment by Whurrhurr** [comment]
update: seems to only really happen if your continent files are saved as binary. generic/custom xml don't seem to have this issue.

**Comment by ontrigger** [comment]
if that is the case then i don't really know if i can do anything about it, i'll probably just leave a warning
