### ISSUE TITLE
[Bug?] Can't edit objectives in cloned vanilla maps.

### ISSUE THREAD

**Issue by TheRant-man** [Luffyyy/BeardLib-Editor#417]
Every time I try to edit objectives in a clone of a vanilla heist I get told "Your map is not setuped correctly". 
![20190913210845_1](https://user-images.githubusercontent.com/55584170/65321387-b8a21a80-dbac-11e9-9e19-f7e962b88f86.jpg)

This doesn't happen on custom heists by other people or in an empty new heist.
![20190919230444_1](https://user-images.githubusercontent.com/55584170/65321398-c3f54600-dbac-11e9-82ed-018261c6d9df.jpg)

**Comment by RexTheWho** [comment]
Cloned heists are missing objective scriptdata.

For now add this to your level in the main.xml and copy over the scriptdata from a custom map.
```
		<script_data_mods directory="scriptdata">
			<mod replacement="objectives.objective" replacement_type="custom_xml" target_ext="objective" target_path="gamedata/objectives">
				<options merge_mode="add" mode="add"/>
			</mod>
		</script_data_mods>
```

**Comment by TheRant-man** [comment]
I tried this but it didn't work?
![20190921140628_1](https://user-images.githubusercontent.com/55584170/65372475-78f53480-dc79-11e9-97f4-230ad89963f2.jpg)
![kuva](https://user-images.githubusercontent.com/55584170/65372478-85798d00-dc79-11e9-8cc4-45437d6685f6.png)
![kuva](https://user-images.githubusercontent.com/55584170/65372479-8a3e4100-dc79-11e9-9591-f5c53e7520b4.png)
(I got those objectives from some other custom map)

**Comment by RexTheWho** [comment]
Needs to be in the `<level>` section

**Comment by TheRant-man** [comment]
aight my bad

**Comment by TheRant-man** [comment]
Weird, everytime I boot up the level in the editro, it messes with main.xlm and moves the string out of <levels> section to the very bottom.

**Comment by TheRant-man** [comment]
And still says I am setuped incorrectly ;w;

**Comment by TheRant-man** [comment]
![kuva](https://user-images.githubusercontent.com/55584170/65372998-0dfb2c00-dc80-11e9-9984-f84e17d60cf3.png)
Just making sure, is this correct? Cuz it gets moved here everytime the game modifies the main.xml

**Comment by RexTheWho** [comment]
Close the game, and then move that `<script_data>` section into the `<level>` and then open the game again.
