### ISSUE TITLE
toggling AreaTrigger causes screen to go black and all audio to dissapear

### ISSUE THREAD

**Issue by lazyRares** [Luffyyy/BeardLib-Editor#420]
exactly as the title says, i have it made so once you click a button the van AreaTrigger is supposed to enable so you can secure bags, however when i do click the button the screen turns black, i cannot look around or do anything and all the audio is gone. however the game is still open and the bots are still running around.

**Comment by Luffyyy** [comment]
Can you give me a project that has this issue?

**Comment by RexTheWho** [comment]
I suspect the issue here may be forgetting to set the area trigger to be for lootbags and when clicking the execute button will secure the player as if they were a lootbag.

**Comment by Luffyyy** [comment]
Remake the issue with actual project next time.
