### ISSUE TITLE
Loading from Eextract is inconsistent

### ISSUE THREAD

**Issue by Dushess** [Luffyyy/BeardLib-Editor#422]
I have full extract in place again, but some items can be loaded and some is not.
Not map related, tried on just new one with same result.

**Comment by Luffyyy** [comment]
Can you maybe elaborate?

**Comment by Dushess** [comment]
Just on my installation tries to make something again (latest game version and latest editor version on that day), placed entire Extract folder bach at same place, but anyway... Some units don't want to be loaded like some missed files. Tried also to download hashlist again, but Extract was from times without mexican haists and other newest stuff.

And also I considered leave PD world again.

**Comment by Luffyyy** [comment]
You'll have to remake the issue with detailed explanation, including which unit causes issues.
