### ISSUE TITLE
[Request] Area Select (Units/Elements)

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#427]
Messing with map clones and it would be very handy to be able to highlight an area and select all units inside (Similar to how the Portals can auto-fill with units that are inside).

**Comment by ontrigger** [comment]
use hold alt-rightclick to select, ctrl-rightclick to deselect

**Comment by RexTheWho** [comment]
Not sure what you mean. Ctrl-Rightclick just selects units normally.

**Comment by ontrigger** [comment]
it should enable drag selecting units inside the box you drew

**Comment by RexTheWho** [comment]
Nothing visually shows. Got a screenshot of what's meant to happen?

**Comment by ontrigger** [comment]
https://gfycat.com/SaneBruisedGuineafowl

**Comment by RexTheWho** [comment]
Doesnt happen on my end. How long has this been a thing?

**Comment by ontrigger** [comment]
almost a year I think. it should work if you disable endless raycast

**Comment by RexTheWho** [comment]
Solved it, Endless selection disabled it. yes.
