### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by MiamiCenterPL** [Luffyyy/BeardLib-Editor#433]
I'm crashing alot while *connecting* elements (manage on executed list)
This is the crash.txt
`Application has crashed: C++ exception
...ardLib-Editor-master/Classes/Map/MissionScriptEditor.lua:67: bad argument #1 to 'pairs' (table expected, got nil)

SCRIPT STACK

update_clbk() @mods/BeardLib-Editor-master/Classes/Map/MissionScriptEditor.lua:67
clbk() @mods/BeardLib-Editor-master/Classes/Map/MissionScriptEditor.lua:482
run_callback() 129
hide() 181
hide() 129
on_escape() 188
on_escape() 205
CloseLastDialog() 105
func() @mods/BeardLib/Hooks/MenuManager.lua:20
core/lib/managers/controller/corecontrollerwrapper.lua:596`

Happens when you leave OnExecuted list empty.

**Comment by ontrigger** [comment]
Are you sure that you're on the latest version? I thought it was fixed

**Comment by MiamiCenterPL** [comment]
I was pretty sure I used latest version, just updated the BeardLib Editor to be sure and that fixes the issue. Thanks <3
