### ISSUE TITLE
Issues i found with the editor

### ISSUE THREAD

**Issue by stevemanny** [Luffyyy/BeardLib-Editor#434]
1. It crashes very often, it can crash for even trying to carry a bag
2. There is no hud
3. Too many bugs (however i can forgive this one as the editor is still under development)
4. Unlike hammer (source game editor), the editor itself has physics, and it can get fustrating.
5. How does one add AI?

Ways of crashing: Carrying bag, loading from extract and thats really all i found thats crashing beardlib editor

Conclusion: The editor is good but needs the bugs fixed before diving deeper...

**Comment by Luffyyy** [comment]
That is not an issue. An issue is reporting **one** issue, avoid grouping them. Make sure your reports are detailed and have a crashlog if you wish any issue to be fixed. 

Unlike Hammer, this is developed as a mod for the game and developed mainly by 2 people (and not always at the same time).

Documentation is sadly missing and the best way is to just ask exisiting map creators through ModWorkshop's Discord. You can also check out the wiki https://wiki.modworkshop.net/books/payday-2/chapter/beardlib-editor
