### ISSUE TITLE
Cant add elements!

### ISSUE THREAD

**Issue by LeoZsuper** [Luffyyy/BeardLib-Editor#438]
As soon as I add any element( for example, unitSequenceTrigger or interaction), the game crashes when starting the map as player(it's loading in editor, but as soon as I want to play as player, it crashes). This happens only when adding elements, units don't give this crash. I have only Beardlib and BeardlibEditor in my mods file. Here is the crash, its always the same:

Application has crashed: C++ exception
[string "lib/managers/navigationmanager.lua"]:3105: attempt to get length of a nil value

SCRIPT STACK

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.93.848
	CPU : Intel(R) Core(TM) i3-6100U CPU @ 2.30GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce 940MX / nvldumd.dll[26.21.14.4166]
	Language : english
	Memory :     16257MB 924KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (2- Realtek High Definition Audio))

**Comment by Luffyyy** [comment]
Does not happen to me. You'll need to provide me a project to test this issue.

**Comment by Luffyyy** [comment]
Closed due to inactivity, I'm assuming it's in your end.
