### ISSUE TITLE
Error-404

### ISSUE THREAD

**Issue by Bobsby** [Luffyyy/BeardLib-Editor#445]
Not necessarily an issue with the mod however the https://modworkshop.net/wiki.php?action=view&id=15 link to see the guide and other important details is giving an 404 error. Thought you might want to know its not working, especially since there are no other guides on how to operate the editor to my knowledge.
(And its very hard to figure out how to do things like scripts with no guide)

**Comment by Luffyyy** [comment]
Forgot to update the links, the wiki has been to wiki.modworkshop.net and BLE guides are here https://wiki.modworkshop.net/books/payday-2/chapter/beardlib-editor
