### ISSUE TITLE
[Element: AlertTrigger] AlertTrigger may not function correctly

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#454]
The UI looks out of order and it seems to not do anything after toggling everything on or off.
Intended effect is meant to hear things like gunfire and alert the police, used to be used on Big Oil Day1, the element is still in there.

**Comment by Luffyyy** [comment]
Not sure about functionality but I am almost certain the beardlib/editor have nothing to do with it. I reorganized the UI for it.
