### ISSUE TITLE
[Environment] Ambient Scale setting should only go from 0-1

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#460]
Setting"Scale" to 1 or higher disables its effects.
This means having the slider go all the way to 10 is not necessary.

![20200119153344_1](https://user-images.githubusercontent.com/26837908/72676892-20bc2b00-3ad1-11ea-8bb5-252c9ad05885.jpg)
![20200119153347_1](https://user-images.githubusercontent.com/26837908/72676893-2154c180-3ad1-11ea-9326-0b972496aa3c.jpg)

**Comment by Luffyyy** [comment]
In the real editor that's the maximum but sure
