### ISSUE TITLE
Payday crash on Map opening in Crime.net

### ISSUE THREAD

**Issue by Bobsby** [Luffyyy/BeardLib-Editor#464]
Opening the map in the editor works fine and with no issues, upon attempting it within Crime.net, it will instantly crash for seemingly no reason. 
I don't know the first place to look, but checking most files I can't see an issue.
Not sure if its a bug or not but I figured best to let you know.
If you can help me, please let me know

**Comment by Luffyyy** [comment]
I need a crashlog. Never report a crash without it. I can't do anything without it.

**Comment by Bobsby** [comment]
[crash.txt](https://github.com/Luffyyy/BeardLib-Editor/files/4099668/crash.txt)
Sorry about that, I completely forgot to add the crash log

**Comment by Luffyyy** [comment]
I'll need the project. My assumption is that the contractor is invalid.

**Comment by Bobsby** [comment]
Heres the project, what should I do to prevent this for next time?
[Stop Bank.zip](https://github.com/Luffyyy/BeardLib-Editor/files/4099845/Stop.Bank.zip)

**Comment by Luffyyy** [comment]
The crimenet video you set either doesn't exist or is not loaded. Plus oddly your main.xml is messed up having some nodes of the narrative module outside of it.

**Comment by Luffyyy** [comment]
here's a fixed main.xml for you.
[main.zip](https://github.com/Luffyyy/BeardLib-Editor/files/4105921/main.zip)

**Comment by Bobsby** [comment]
Thank you for the help
