### ISSUE TITLE
[Element PlayerStyle] Missing suit ids

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#468]
ElementPlayerStyle can be used to swap players suit, used in the secret to unequip the murky gear, just have to load the suits and it will set players suit just fine.

Its just missing all the custom suit ids in the select box, only shows '_scrubs'

**Comment by Dushess** [comment]
Can it use every model or operates exactly new suit system?

**Comment by Luffyyy** [comment]
It uses the suit system, if you want to add to it you need to add to the tweak data.
