### ISSUE TITLE
[Prefabs] Crash on spawning large scale prefabs

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#469]
Crash when spawning prefab with many many units inside.

[Prefab.zip](https://github.com/Luffyyy/BeardLib-Editor/files/4126629/Prefab.zip)

No crashlog is provided by the game when crashing.

**Comment by Luffyyy** [comment]
Could just be diesel sadly or 32bit limit.

**Comment by Luffyyy** [comment]
Running it seems to point to a missing unit or something 

        _create_statics_unit()  @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:647  
                 create_unit()  @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:565  
                   SpawnUnit()  @mods/BeardLib-Editor/Classes/MapEditor.lua:402     
                all_ok_spawn()  @mods/BeardLib-Editor/Classes/Map/StaticEditor.lua:1375
