### ISSUE TITLE
[AddFiles] Using shortcut addfiles in Maps doesnt list them in the units list

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#471]
Test map here: https://puu.sh/F5TlS/bab4779190.zip

In the Main.xml I included these assets and because of that effects stopped working ingame and loaded assets were no long added to the units list in editor.
```
    <AddFiles directory="assets">
        <unit_mat path="units/pd2_mod_pvp/uniforms/swat/acc_swat_1_fps/acc_swat_1_fps" unload="true"/>
        <unit_mat path="units/pd2_mod_pvp/uniforms/swat/acc_swat_1_suit_man/acc_swat_1_suit_man" unload="true"/>
        <material_config path="units/pd2_mod_pvp/uniforms/swat/acc_swat_1_suit_man/acc_swat_1_suit_man_contour" unload="true"/>
        <unit_mat path="units/pd2_mod_pvp/uniforms/swat/acc_swat_1_suit_fem/acc_swat_1_suit_fem" unload="true"/>
        <material_config path="units/pd2_mod_pvp/uniforms/swat/acc_swat_1_suit_fem/acc_swat_1_suit_fem_contour" unload="true"/>
    </AddFiles>
```

**Comment by RexTheWho** [comment]
Edit, this issue applies to add.xml in a level. Using shortcuts like unit_mat will not list them as loaded while being loaded.

**Comment by RexTheWho** [comment]
New example: check `\levels\carshop2\add.xml` for the testing unit `units/pd2_mod_cs2/architecture/int/int_carshop_02`.
[carshop2.zip](https://github.com/Luffyyy/BeardLib-Editor/files/4796228/carshop2.zip)

**Comment by Luffyyy** [comment]
Closing for now. The issue may stem from other reasons. Until you stumble upon it again.
