### ISSUE TITLE
[Feature Request] add an option to highlight units that are currently in the portal you have selected

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/BeardLib-Editor#474]
title, having to scroll down to the bottom of the selection list for every unit to see what portal they're in can get very annoying if you use multiple portals. also it'd make it easier to see what units are in the currently selected portal.

Feb 15 edit: apparently this used to be an actual feature but then it either got removed or was disabled because of a bug.

**Comment by Luffyyy** [comment]
Borked at some point, fixed.
