### ISSUE TITLE
[Crash] Trying to open sound menu CTDs

### ISSUE THREAD

**Issue by TheRant-man** [Luffyyy/BeardLib-Editor#475]
Every time I try to open the menu for sound settings my editor crashes to desc top.

----------------------------------------------------------------------

Sat Feb 15 11:21:30 2020

Application has crashed: C++ exception
[string "core/lib/utils/coretable.lua"]:224: bad argument #1 to 'pairs' (table expected, got nil)

SCRIPT STACK

get_key() core/lib/utils/coretable.lua:224
build_menu() @mods/BeardLib-Editor-master/Classes/Map/SoundLayerEditor.lua:157
final() @mods/BeardLib-Editor-master/Classes/Map/WorldDataEditor.lua:494
RunCallback() 1173
MousePressed() 1299
MousePressed() 1322
MousePressed() 1322
MousePressed() 1322
mouse_press() 481
lib/managers/mousepointermanager.lua:341

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

**Comment by TheRant-man** [comment]
The crash occurs regardless of the heist, vanilla, custom or a cloned heist all sahre this issues. i've also tried reinstalling the editor and redownloading the data package.

**Comment by Luffyyy** [comment]
As mentioned above, the issue seems to happen to both of you and I cannot reproduce it.

**Comment by Teacyn** [comment]
> 
> 
> As mentioned above, the issue seems to happen to both of you and I cannot reproduce it.

I am also experiencing this repeatedly. Same crashlog.

**Comment by Luffyyy** [comment]
Are you running the last commit with last BeardLib commit?

**Comment by Teacyn** [comment]
> Are you running the last commit with last BeardLib commit?

Apologies for late reply, es I was I've been getting this crash for several beardlib versions too.

**Comment by TheRant-man** [comment]
I am on the latest commit

**Comment by Luffyyy** [comment]
Give me the project you have the problem in

**Comment by TheRant-man** [comment]
Here
[PLD2z.zip](https://github.com/Luffyyy/BeardLib-Editor/files/4850158/PLD2z.zip)

**Comment by Luffyyy** [comment]
![image](https://user-images.githubusercontent.com/11510099/86100327-5b36e480-bac1-11ea-878b-721e52d2ed35.png)
Yep still doesn't happen. I suggest removing some mods until it stops crashing.

**Comment by TheRant-man** [comment]
Aight

**Comment by Teacyn** [comment]
Still able to replicate with no mods other than Editor + dependencies.

**Comment by Luffyyy** [comment]
Dependencies?

**Comment by Teacyn** [comment]
> Dependencies?

Beardlib itself + SBLT

**Comment by Luffyyy** [comment]
I made a change that should fix this, but this generally shouldn't even happen if I had to assume, the hook CoreSoundEnvironmentManager fails somewhere, or something is overriding it. 

[SoundEnvironmentManager.zip](https://github.com/Luffyyy/BeardLib-Editor/files/6285687/SoundEnvironmentManager.zip)
Drop to hooks and send BLT log.
