### ISSUE TITLE
[nav_data] Missing vis_groups toggle for nav surfaces

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#478]
In the nav_manager_data.nav_data file there's entrys for vis_groups, this will hide/show Ai in that area of navigation.

```
<entry key="vis_groups" type="table">
 <entry index="1" type="boolean" value="true"/>
 <entry index="2" type="boolean" value="false"/>
</entry>
```

**Comment by Luffyyy** [comment]
Pretty sure it's automatic

**Comment by Luffyyy** [comment]
Since this isn't ever edited by any GUI in the decompiled code, I'm going to close this issue. Implementing such a feature, if attempted would probably be complicated. The navigation builder class is pretty complicated by itself.
