### ISSUE TITLE
[Request] ability to hand input set_orthographic_screen coords

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#479]
To get proper preplanning images I had to delete
`self._camera_object:set_orthographic_screen( -(res.x/2)*self._mul, (res.x/2)*self._mul, -(res.y/2)*self._mul, (res.y/2)*self._mul )`

And replace it with my desired scale and teleport the camera to the center location
`self._camera_object:set_orthographic_screen( -8000, 8000, -8000, 8000 )`

The request is when in orthographic mode there be a a camera position and orthographic screen value, Something like...
Camera Location: X Y Z
Orthographic scale: X Y _(Where X = X and -X)_

**Comment by Luffyyy** [comment]
btw, you can go up and down via Q and E
