### ISSUE TITLE
music="no_music" causes crash when pressing tab in game

### ISSUE THREAD

**Issue by LulsCupcake** [Luffyyy/BeardLib-Editor#480]

**Comment by LulsCupcake** [comment]
![image](https://user-images.githubusercontent.com/26014431/76194690-e7846b00-61a3-11ea-999c-99215333836f.png)

**Comment by Luffyyy** [comment]
Needs more infromation

**Comment by LulsCupcake** [comment]
So this was pretty much after OVK added some more stealth music to the game, they removed the "music == "no_music" string that could be attached to levels. This is probably more of a beardlib issue that an editor issue and I apologize.

This is used primarily in Zombie gamemodes cause there is no music, but having the no_music string crashes the game when you press tab.

its found in "lib/managers/musicmanager"

**Comment by Luffyyy** [comment]
What is the crash though?

**Comment by Luffyyy** [comment]
Reopen in BeardLib
