### ISSUE TITLE
[Element: InstancePoint] Mission Placed instances locations being moved

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#482]
When pointing an instance to another location the mission placed instance will be saved in that location instead of where they originally were (usually placed off map)

**Comment by Luffyyy** [comment]
Not sure I'm following

**Comment by RexTheWho** [comment]
I think this mightve been fixed at some point, but the report as something along the lines of:
- Mission Spawned Instances usually get put somewhere random off the map
- Executing an InstancePoint element positions it like it should
- Saving after that would save its position after being spawned over by the InstancePoint
End result being the instance is misplaced on reload.

**Comment by Luffyyy** [comment]
Now it will move the instance to the element but once you click the instance, it will go back to its original place
