### ISSUE TITLE
Game is keep crashing on start

### ISSUE THREAD

**Issue by PhillTV** [Luffyyy/BeardLib-Editor#483]
Hey,

i have a question. my game is crashing when i start and when i'm ingame it'll crash after a certain time and i dont know what to do

Crash date: 17.03.2020 16:51:21

PAYDAY 2 Crash log
Application has crashed: C++ exception
bad allocation
-------------------------------
Callstack:
           gameoverlayrenderer  (???)     VulkanSteamOverlayProcessCapturedFrame              
           gameoverlayrenderer  (???)     VirtualFreeWrapper                                  
                    igdumdim32  (???)     ???                                                 
-------------------------------
Current thread: Renderer
-------------------------------
System information:
	Application version : 1.94.862
	CPU : Intel(R) Core(TM) i3-6006U CPU @ 2.00GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : Intel(R) HD Graphics 520 / igdumdim32.dll[25.20.100.6446]
	Language : german
	Memory :     8060MB 228KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Lautsprecher (Realtek High Definition Audio))

Lua information
Lua Hook: not present
BLT Hook data: present

Lua BLT Log (+/- 1 minute)
04:51:26 PM Log:  (C:\Users\ZNix\source\repos\SuperBLT\src\http\http.cpp:57) CURL CLOSED

Lua BLT Mods list
   Name: SuperBLT, Version: 1.1.6.0, Author: ZNix, James Wilkinson
   Name: BeardLib, Version: 3.0x, Author: GREAT BIG BUSHY BEARD & Luffy
   Name: No Post Processing! + Outlines Working + No Blue Filter on Main Menu Reborn!, Version: 5 (Reborn), Author: Seamlink
   Name: PocoHud3, Version: based on v0.35 (r467), Author: zenyr

Installed PDMods/Override list
   Name: Federal Inventory, Type: mod_override, State: Unrecognized, Author: <UNKNOWN>

-----

What can i do to prevent game crasher?

**Comment by Luffyyy** [comment]
No idea that doesn't look like BeardLib editor's fault.
