### ISSUE TITLE
Game is crashing when I opening any heist(if it not mine)

### ISSUE THREAD

**Issue by THEHOMAK** [Luffyyy/BeardLib-Editor#485]
Crashlog:
----------------------------------------------------------------------

Sat Mar 21 00:32:32 2020

Application has crashed: C++ exception
mods/BeardLib-Editor-master/Classes/Utils.lua:96: attempt to index global 'BLEP' (a nil value)

SCRIPT STACK

HasProjectionLight() @mods/BeardLib-Editor-master/Classes/Utils.lua:342
HasAnyProjectionLight() @mods/BeardLib-Editor-master/Classes/Utils.lua:337
_setup_editor_unit_data() @mods/BeardLib-Editor-master/Hooks/WorldDefinition.lua:585
original() @mods/BeardLib-Editor-master/Hooks/WorldDefinition.lua:672
assign_unit_data() @mods/base/req/core/Hooks.lua:260
_create_statics_unit() @mods/BeardLib-Editor-master/Hooks/WorldDefinition.lua:659
create() @mods/BeardLib-Editor-master/Hooks/WorldDefinition.lua:196
create_world() core/lib/utils/dev/editor/worldholder.lua:110
init_game() lib/setups/gamesetup.lua:653
core/lib/setups/coresetup.lua:422

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.94.862
	CPU : AMD Phenom(tm) II X4 965 Processor (2 cores); SSE; SSE2; SSE3
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 650 Ti BOOST / nvldumd.dll[26.21.14.4141]
	Language : english
	Memory :     16343MB 192KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Динамики (Realtek High Definition Audio)

Is there any solution?

**Comment by Luffyyy** [comment]
Make sure you have SuperBLT.
