### ISSUE TITLE
Non-default mission scripting is very buggy

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#486]
Working in a second mission file causes issues like randomly deleted elements and links not being shown until reloading.

Setting elements to be in the other scripts after being placed causes them to be deleted also and not be added to the other mission script file.

**Comment by Luffyyy** [comment]
Fixed 2 issues relating to this: changing scripts would delete the element and elements list when selecting elements for certain values will now show only the current script (except ExecuteInOtherMission which apparently was broken lol).

If the links issue perstist, make a new issue. Try to add more information as well as reproduce steps.
