### ISSUE TITLE
Crash when trying to enter the sound menu

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/BeardLib-Editor#495]
Application has crashed: C++ exception
[string "core/lib/utils/coretable.lua"]:224: bad argument #1 to 'pairs' (table expected, got nil)

SCRIPT STACK

get_key() core/lib/utils/coretable.lua:224
build_menu() @mods/BeardLib-Editor-master/Classes/Map/SoundLayerEditor.lua:157
final() @mods/BeardLib-Editor-master/Classes/Map/WorldDataEditor.lua:494
RunCallback() 1184
MousePressed() 1310
MousePressed() 1311
MousePressed() 1311
MousePressed() 1311
mouse_press() 485
lib/managers/mousepointermanager.lua:345

repro steps: load into any level in editor mode, click on Sound.

**Comment by Luffyyy** [comment]
Cannot reproduce.

**Comment by Luffyyy** [comment]
Dup of #475
