### ISSUE TITLE
[REQUEST] Setting for Displaying All Shaders

### ISSUE THREAD

**Issue by GHBDougley** [Luffyyy/BeardLib-Editor#496]
In the editor currently, some advanced shaders (like bloom) are disabled in the editor view.

Was wondering, for making .environment creation easier, can we get a setting somewhere in the UI to display all shaders in editor view?

**Comment by RexTheWho** [comment]
Also Overkills editor footage also shows you can trigger environment portals with the editor camera. I think that would actually be very useful for environment work.

**Comment by Luffyyy** [comment]
What do you mean disabled? Every modifier has to have an item created specficially for it, pretty much all of them were taken from what overkill had in their own editor

**Comment by GHBDougley** [comment]
Not the settings, the way it appears in the game world.

For instance, Bloom doesn't show up in editor camera view, so you can't see your changes to it until you apply the environment to your level, and then drop into the heist.  It slows down the entire process and makes very precise bloom edits a bit of a chore to carry out.

**Comment by Whurrhurr** [comment]
in the editor all post processing effects are disabled, having an option to turn certain ones on or off would be nice.
