### ISSUE TITLE
[Crash] attempting to save a map project outside of the "Maps" folder crashes

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/BeardLib-Editor#508]
Application has crashed: C++ exception
mods/BeardLib-Editor-master/Classes/ProjectManager.lua:241: attempt to index local 'mod' (a nil value)

SCRIPT STACK

save_main_xml() @mods/BeardLib-Editor-master/Classes/ProjectManager.lua:117
save_main_xml() @mods/BeardLib-Editor-master/Classes/Map/InEditorOptions.lua:340
save() @mods/BeardLib-Editor-master/Classes/Map/InEditorOptions.lua:290
save() @mods/BeardLib-Editor-master/Classes/Map/InEditorOptions.lua:308
clbk() @mods/BeardLib-Editor-master/Classes/Map/UpperMenu.lua:136
final() @mods/BeardLib-Editor-master/Classes/Map/UpperMenu.lua:69
RunCallback() @mods/BeardLib/Classes/UI/MenuUI/Item.lua:1224
MousePressed() @mods/BeardLib/Classes/UI/MenuUI/Item.lua:1350
MousePressed() @mods/BeardLib/Classes/UI/MenuUI/Item.lua:1376
MousePressed() @mods/BeardLib/Classes/UI/MenuUI/Item.lua:1376
mouse_press() @mods/BeardLib/Classes/UI/MenuUI/MenuUI.lua:484
lib/managers/mousepointermanager.lua:345

resmod has a map_overrides folder, attempting to save any map that's in there saves what changes you've made and crashes.

**Comment by Luffyyy** [comment]
Unsupported.

**Comment by Luffyyy** [comment]
To add information: the way the editor works, it focuses on the map framework and to make sure no issues are caused it probably should stay this way for the time being. At some point hopefully we can support other frameworks.
