### ISSUE TITLE
[Crash] Crash on save

### ISSUE THREAD

**Issue by VxWolf** [Luffyyy/BeardLib-Editor#509]
```
Application has crashed: C++ exception
mods/BeardLib-Editor-master/Classes/ProjectManager.lua:241: attempt to index local 'mod' (a nil value)



SCRIPT STACK

save_main_xml() @mods/BeardLib-Editor-master/Classes/ProjectManager.lua:117
save_main_xml() @mods/BeardLib-Editor-master/Classes/Map/InEditorOptions.lua:340
@mods/BeardLib-Editor-master/Classes/Map/InEditorOptions.lua:290
```

I may have tried to duplicate an element while the autosave was occurring but that may be unrelated

**Comment by VxWolf** [comment]
that was unrelated, crashed while i was not actively working on a map

**Comment by Luffyyy** [comment]
Are you running maps through the 'Maps' folder? other frameworks are not supported at the moment.

**Comment by VxWolf** [comment]
yes it's in the maps folder, also normal saves cause the crash too

**Comment by VxWolf** [comment]
Nevermind my project has been doing this thing where it splits the narrative and the map for some reason
