### ISSUE TITLE
[Project UI] Projects assume payout/min xp/max xp causing issues with Holdout maps

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#515]
When making Holdout contractor heists the narrative needs to contain a single `<max_mission_xp="111111" min_mission_xp="111111" payout="0">`
Using the Project UI causes beardlib to replace that working XP/Payout with the incompatible value_node setup you usually see here:
```
		<payout>
			<value_node value="4000"/>
			<value_node value="8000"/>
			<value_node value="20000"/>
			<value_node value="40000"/>
			<value_node value="100000"/>
			<value_node value="100000"/>
			<value_node value="100000"/>
		</payout>
```

**Comment by Luffyyy** [comment]
I'm assuming an update to the game fixed most of these issues. If you want to make maps like that, for now put the same XP/Payout whatever to be the same for these maps. If it's really annoying I might make it change the UI to have a single option, but that's more of a feature request, so you can just open another issue.
