### ISSUE TITLE
Editor crashes, when saving a project.

### ISSUE THREAD

**Issue by TheRant-man** [Luffyyy/BeardLib-Editor#519]
When I press the save button, the map WILL save the changes but will crash the editor right after.

The map is inside the maps folder and it's name or folders do not contain dots. 

Crashlog below.
----------------------------------------------------------------------

Sun Jul 05 03:32:53 2020

Application has crashed: C++ exception
mods/BeardLib-Editor/Classes/ProjectManager.lua:241: attempt to index local 'mod' (a nil value)

SCRIPT STACK

save_main_xml() @mods/BeardLib-Editor/Classes/ProjectManager.lua:117
save_main_xml() @mods/BeardLib-Editor/Classes/Map/InEditorOptions.lua:341
@mods/BeardLib-Editor/Classes/Map/InEditorOptions.lua:291

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlSetLastWin32Error                                
                    KERNELBASE  (???)     CreateFileW                                         
                    KERNELBASE  (???)     CreateFileW                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     NvOptimusEnablement                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.95.896
	CPU : AMD Ryzen 5 3600X 6-Core Processor (6 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : NVIDIA GeForce GTX 1060 6GB / nvldumd.dll[26.21.14.4614]
	Language : english
	Memory :     16337MB 968KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Headphones (High Definition Audio Device))

**Comment by Luffyyy** [comment]
Make sure that the map is opened in Maps folder and has no special characters like a period

**Comment by LulsCupcake** [comment]
Also make sure that the project name is the same as the folder name in the maps folder
