### ISSUE TITLE
Game Crashes Upon Attempting to Create Cloned Map

### ISSUE THREAD

**Issue by Neslon-Poggers** [Luffyyy/BeardLib-Editor#523]
### **Describe the crash**
whenever I try cloning a map, the game will crash immediately after I finish naming my levels/level. i've redownloaded the latest beardlib from github, and the editor along with its package data (which shouldnt even be separate imo)
### **To Reproduce**
just try creating a new cloned map lol

### **Crashlog**
Application has crashed: C++ exception
...Lib-Editor-master/Classes/Project/ProjectLevelEditor.lua:168: attempt to index local 'inner_chain_level' (a number value)

SCRIPT STACK

clbk() @mods/BeardLib-Editor-master/Classes/Project/ProjectLevelEditor.lua:94
run_callback() @mods/BeardLib/Classes/UI/Dialogs/InputDialog.lua:53
hide() @mods/BeardLib/Classes/UI/Dialogs/MenuDialog.lua:183
pre_key_press() @mods/BeardLib/Classes/Managers/MenuDialogManager.lua:138
@mods/BeardLib/Classes/UI/MenuUI/MenuUI.lua:374

-------------------------------

**Comment by Luffyyy** [comment]
Trying to clone san martin bank seems to work fine, what map crashes exactly?

**Comment by Luffyyy** [comment]
Reopen the issue if this still happens
