### ISSUE TITLE
Element RandomInstanceInputEvent does not save its instances list

### ISSUE THREAD

**Issue by VxWolf** [Luffyyy/BeardLib-Editor#524]
Adding instances to the instances list of the RandomInstanceInputEvent is not functional, they do not save. This renders it useless.

1. Add some instances with InstanceInputs in them.
2. Add a RandomInstanceInputEvent into the level.
3. In the element properties, click Manage Instances List(instances), and add some of the instances you placed earlier
4. Close the list window. Take note of how the RandomInstanceInputEvent does not actually link to the instances.

**Comment by Luffyyy** [comment]
Fixed by #553
