### ISSUE TITLE
[Effect Editor] scaled channels fail to disable looping

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#528]
**Describe the bug**
When setting size_scale_keys for example turning loop on will add `loop="true"` but toggling it off will not save as `false` or be removed.

**To Reproduce**
Open an effect that loops a key and toggle `loop` off. Saving or updating the effect will not remove the loop setting.
![image](https://user-images.githubusercontent.com/26837908/88137549-5bd51d80-cc1e-11ea-8b23-aaff6f717cdb.png)

**Comment by Luffyyy** [comment]
Uh should that matter?

**Comment by RexTheWho** [comment]
yes, telling an animation to stop looping and it doesnt stop looping is a bit of an issue.

**Comment by Luffyyy** [comment]
Oh I assumed when it's gone it's off

**Comment by RexTheWho** [comment]
Its never gone, turning looping off leaves the looping="true" in the files.
