### ISSUE TITLE
[Element] Random Instance Input Event doesnt saved managed instances list

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#536]
**Describe the bug**
Selecting instances in Manage Instances List doesnt save to the element, shown when opening the menu again.

**To Reproduce**
- Add random_instance_input_event element to the map
- Select it and open the Manage Instances List(instances) window
- Select instances in your level
- Exit window
- Open window and see the instances are deselected

**Comment by MiamiCenterPL** [comment]
Fixed #553
