### ISSUE TITLE
Build Navigation Compares 2 nil values

### ISSUE THREAD

**Issue by jaschutte** [Luffyyy/BeardLib-Editor#540]
**Describe the crash**
Building navigation crashes payday 2 and trying to re-opening that level will crash it as well. Making you unable edit the level again. Also crashing when trying to enter using safemode.

**To Reproduce**
Honestly I've no idea. I placed down more navigation surfaces and then press build and it crashed. Trying to edit that level and it crashes on startup.

**Crashlog**
Application has crashed: C++ exception
[string "lib/managers/navfieldbuilder.lua"]:829: attempt to compare two nil values

SCRIPT STACK

task_clbk() lib/managers/navfieldbuilder.lua:420
update() lib/managers/navfieldbuilder.lua:80
update() @mods/BeardLib-Editor-master/Hooks/NavigationManager.lua:46
update() lib/setups/gamesetup.lua:726
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:557

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlSetLastWin32Error                                
                    KERNELBASE  (???)     CreateFileW                                         
                    KERNELBASE  (???)     CreateFileW                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                   steamclient  (???)     hid_write_output_report                             
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     NvOptimusEnablement                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 

-------------------------------

Current thread: Main

-------------------------------

System information:

	Application version : 1.96.909
	CPU : Intel(R) Core(TM) i7-10875H CPU @ 2.30GHz (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 2070 Super / nvldumd.dll[26.21.14.4294]
	Language : english
	Memory :     16288MB 544KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek(R) Audio))

**Comment by Luffyyy** [comment]
Sorry for the slow response but could you send me that map?

**Comment by jaschutte** [comment]
[The Suite.zip](https://github.com/Luffyyy/BeardLib-Editor/files/6272664/The.Suite.zip)
My apologies if you see that I did some stupid stuff, I'm still new to mapping

**Comment by Luffyyy** [comment]
Well dunno I tried doing multiple tests and it's quite a complicated crash to fix, it's a problem inside the code that generates the navigation. I recommend that you delete all navigation and start over, you map is also very open, maybe it doesn't like that.

**Comment by ontrigger** [comment]
This is caused by nav surfaces having duplicate editor ids. 
The editor will now show the duplicated unit when building ai.
