### ISSUE TITLE
Missing Data [BUG]

### ISSUE THREAD

**Issue by RmxMi** [Luffyyy/BeardLib-Editor#541]
I have downloaded BeardLib, SuperBLT, and BearLib Editor but the editor option in the menu doesn't show up, when I open payday 2 I get this popup and there is no update available, as it says and I've reinstalled everything, Payday 2, mods, disabled all mods. It just doesn't work I own a copy of Payday 2 on Steam and I've used the editor before but when I installed payday 2 again after a break of 1 year it doesn't work.
![hgfsjwtsafdj](https://user-images.githubusercontent.com/63404395/91717692-4bf01800-eb92-11ea-8b43-67dbb58bdbd8.png)

**Comment by Luffyyy** [comment]
Show me your beardlib mods manager

**Comment by RmxMi** [comment]
![image](https://user-images.githubusercontent.com/63404395/91850931-aa82c800-ec5e-11ea-97b6-7ae3844052f8.png)
(new player don't roast me for meth helper and silent assasin)

**Comment by Luffyyy** [comment]
**beardlib** mods manager. That's BLT. Press the Beard icon with the number on the main menu.

**Comment by RmxMi** [comment]
Fixed it thanks. Now to learn this editor XD
