### ISSUE TITLE
Spawning an instance of levels/instances/unique/brb/office_floor/world crashes the game

### ISSUE THREAD

**Issue by ChildishGiant** [Luffyyy/BeardLib-Editor#543]
**Crashlog**
[crashlog.txt](https://github.com/Luffyyy/BeardLib-Editor/files/5189065/crashlog.txt)
[crash.txt](https://github.com/Luffyyy/BeardLib-Editor/files/5189066/crash.txt)

**Comment by RexTheWho** [comment]
Strange issue- happens on my end also.
Making a clone of the instance loads just fine, in the meantime try that.

**Comment by Luffyyy** [comment]
To my assumption, this instance uses a package of the level it is based of (brooklyn bank). That being said, I'll most likely implement something that automatically loads that unit with the new load from database feature coming soon.
