### ISSUE TITLE
Toggling enabled on a painting in gallery heist crashes

### ISSUE THREAD

**Issue by ChildishGiant** [Luffyyy/BeardLib-Editor#544]
**Describe the crash**
Toggling enabled on a painting in gallery heist crashes.

**To Reproduce**
Open up gallery
Toggle enabled on one of the painting walls
Select one of the paintings with bars
Toggle enabled -> crash

**Crashlog**
[crash.txt](https://github.com/Luffyyy/BeardLib-Editor/files/5193252/crash.txt)

**Comment by Luffyyy** [comment]
Not the reason it happens, it's the same #546. Wait until this DLL is removed, or perhaps update your SBLT it might not be updated and so it fails to load the DLL.
