### ISSUE TITLE
[Environments] Dome Occlusion generates wrong

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#545]
**Describe the bug**
When baking dome occlusion you get a misaligned texture.
Additionally the editor cursor is visible in the texture.
![image](https://user-images.githubusercontent.com/26837908/92598265-29b97100-f2db-11ea-82ff-ff948d6bc60c.png)
Should look more like bankheists occlusion where the middle of the texture has a building
![image](https://user-images.githubusercontent.com/26837908/92598826-f1666280-f2db-11ea-8307-43b12d32413f.png)

**To Reproduce**
- Spawn a dome occlusion unit in a custom level.
- Position it away from the origin of the level (to cover the whole map)
- World > Environment > Dome Occlusion: Generate (Any resolution or size)
- You should get a misaligned dome occlusion texture

**Comment by Luffyyy** [comment]
Dome occlusions are not misaligned really, you can test a new map (Dragon heist) and the editor is spot on with the location.
There is however a slight weirdness with how the editor makes the textures, 
![image](https://user-images.githubusercontent.com/11510099/114178319-3fad1400-9946-11eb-9ad0-69bf59398258.png)
Top is editor's result and bottom is ovk's. Not sure at the moment if it does anything significant.
