### ISSUE TITLE
In game option to enable/disable supermod.xml

### ISSUE THREAD

**Issue by ChildishGiant** [Luffyyy/BeardLib-Editor#547]
**Is your feature request related to a problem? Please describe.**
I often open up the mod install folder to rename supermod.xml to allow online play.

**Describe the solution you'd like**
Either an option in game to disable/re-enable supermod.xml or having it automatically disabled when opening up online matchmaking.

**Comment by Luffyyy** [comment]
I'm waiting for a feature in SBLT which would simplify making an option for this.

**Comment by Luffyyy** [comment]
Good news: the update should come really soon, probably tomorrow.

**Comment by Luffyyy** [comment]
Added!
