### ISSUE TITLE
Beardlib editor crashes when executing SpawnEnemyDummy

### ISSUE THREAD

**Issue by Nicolajsej123** [Luffyyy/BeardLib-Editor#550]
For some reason it crashes when i try to execute it, i have no mods other than Blt SuperBLT and the beardlib editor.

Application has crashed: C++ exception
[string "lib/units/enemies/cop/copmovement.lua"]:1480: attempt to index field '_nav_tracker' (a nil value)

SCRIPT STACK

post_init() lib/units/enemies/cop/copmovement.lua:520
post_init() lib/units/enemies/cop/copbase.lua:68
lib/units/enemies/cop/copsound.lua:17
safe_spawn_unit() =[C]
produce() lib/managers/mission/elementspawnenemydummy.lua:77
on_executed() lib/managers/mission/elementspawnenemydummy.lua:149
execute_element() @mods/BeardLib-Editor-master/Hooks/MissionManager.lua:502
final() @mods/BeardLib-Editor-master/Hooks/MissionManager.lua:260
RunCallback() @mods/BeardLib/Classes/UI/MenuUI/Item.lua:1224
MousePressed() @mods/BeardLib/Classes/UI/MenuUI/Item.lua:1350
MousePressed() @mods/BeardLib/Classes/UI/MenuUI/Item.lua:1376
MousePressed() @mods/BeardLib/Classes/UI/MenuUI/Item.lua:1376
MousePressed() @mods/BeardLib/Classes/UI/MenuUI/Item.lua:1376
MousePressed() @mods/BeardLib/Classes/UI/MenuUI/Item.lua:1376
mouse_press() @mods/BeardLib/Classes/UI/MenuUI/MenuUI.lua:484
lib/managers/mousepointermanager.lua:345

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlDosSearchPath_Ustr                               
                         ntdll  (???)     RtlFreeHeap                                         
                         ntdll  (???)     RtlSetLastWin32Error                                
                    KERNELBASE  (???)     CreateFileW                                         
                    KERNELBASE  (???)     CreateFileW                                         
                         ntdll  (???)     ZwQueryVirtualMemory                                
                    KERNELBASE  (???)     VirtualQueryEx                                      
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
                    KERNELBASE  (???)     SetUnhandledExceptionFilter                         
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main

-------------------------------

System information:
	Application version : 1.96.909
	CPU : AMD Ryzen 5 1400 Quad-Core Processor (4 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1
	DirectX : 12.0 
	GPU : AMD Radeon RX 5700 XT / aticfx32.dll[26.20.14038.2009]
	Language : english
	Memory :     16268MB 868KB
	OS : 6.2.9200 () 0x300-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Øresnegl på headset (HyperX Virtual Surround Sound)

**Comment by Luffyyy** [comment]
%localappdata\payday 2\ crash.txt

**Comment by Nicolajsej123** [comment]
There we go

**Comment by MiamiCenterPL** [comment]
@Nicolajsej123 This is caused becouse of Navigation Data beeing corrupted / empty. 
Build your Navigation Data, then it should work.
