### ISSUE TITLE
Text units numbers get shortened without choice after reloading the save.

### ISSUE THREAD

**Issue by Croqui42** [Luffyyy/BeardLib-Editor#557]
Typing Any number with "0" in front of it, for example 01, 02, (ect...) get the 0 removed after the next reload of the map, leaving only the 1, 2...

Note : writing only a 0 leave it unaffected, a lone 0 stay.

Tested with units : 
units/pd2_dlc_berry/props/editable_text_euro_stencil/editable_text_euro_stencil
units/pd2_dlc_chew/props/editable_text_futura/editable_text_futura

[Before / after reloads](https://imgur.com/a/triHiSb)

**Comment by Luffyyy** [comment]
Cannot reproduce
