### ISSUE TITLE
Any good tutorials out here?

### ISSUE THREAD

**Issue by RmxMi** [Luffyyy/BeardLib-Editor#559]
I'm frustrated that I've searched google for some tutorials so I can fuck around with this editor but most of them just don't really teach you anything and there is no clear tutorial.

Can someone link me a good tutorial for BeardLib-Editor?

**Comment by Luffyyy** [comment]
Unfortunately this project is mostly halted and I do not have time to do such things (and never had as I had to develop the project mostly alone). However it is wrong to assume there are no tutorials, some users have helped with this a while ago: https://youtu.be/B255wsELiLs If you need further help I recommend joining either the discord linked in that video or modworkshop. You might find people that are willing to help with troubleshooting and whatnot.
