### ISSUE TITLE
Prefabs not showing in editor

### ISSUE THREAD

**Issue by Skemiil** [Luffyyy/BeardLib-Editor#560]
When I go into the editor and click prefabs nothing is showing up I need help.
![no prefabs](https://user-images.githubusercontent.com/45086008/104989130-9a317680-59ce-11eb-9a9d-b5c0c9357b0f.JPG)

**Comment by Luffyyy** [comment]
You sure you made/installed any? They're supposed to be in Maps/prefabs

**Comment by Luffyyy** [comment]
Closed due to inactivity
