### ISSUE TITLE
GUI does not show up when starting heist.

### ISSUE THREAD

**Issue by ll0N3** [Luffyyy/BeardLib-Editor#563]
**BUG:**
Whenever testing my heist, no gui, no health thing, not even objectives appeared, but i could still hear the "dun dwa duuuun" sound of the objective, and still interact with surroundings. How do I fix this?

**Comment by MiamiCenterPL** [comment]
While in-game (testing) click 0 on your keyboard, that should work.

**Comment by ll0N3** [comment]
> While in-game (testing) click 0 on your keyboard, that should work.

Okay! I'll try that. Thanks for the help!
