### ISSUE TITLE
Empty level when loading instance

### ISSUE THREAD

**Issue by MiamiCenterPL** [Luffyyy/BeardLib-Editor#564]
Basically when you open up any custom instance in editor it loads an blank level without continent and mission.
It only have one Nav_Surface, altough if you click it it just crashes.
If you want heist that uses custom instances you can test it on my Cargoship raid;
https://modworkshop.net/mod/25979

**To Reproduce**
https://i.imgur.com/5qPZ5ne.jpg
https://i.imgur.com/R9Gedy8.png

**Comment by Luffyyy** [comment]
Your custom instances are not setup properly, they're missing things. I'd recommend recreating them from the editor.

**Comment by Luffyyy** [comment]
To clarify, the include is missing continents.continents for example along other things. I also see editor_only continents there which shouldn't generally be in instances afaik
