### ISSUE TITLE
generating nav isn't working

### ISSUE THREAD

**Issue by asshole123141** [Luffyyy/BeardLib-Editor#568]
**Describe the bug**
its getting stuck at 1 of 24

![20210410144910_1](https://user-images.githubusercontent.com/82258403/114262893-9aa93e80-9a0c-11eb-84d7-7a3cf85bb783.jpg)

**Comment by ontrigger** [comment]
map link?

**Comment by ontrigger** [comment]
This is likely caused by the map area being too big, not too much you can do here other than to just wait for it to finish.

**Comment by asshole123141** [comment]
> This is likely caused by the map area being too big, not too much you can do here other than to just wait for it to finish.

how long do "big" maps usually take?
