### ISSUE TITLE
prefab crash

### ISSUE THREAD

**Issue by asshole123141** [Luffyyy/BeardLib-Editor#570]
**Describe the crash**
selecting a specific prefab crashes the game

**To Reproduce**
https://modworkshop.net/mod/24458
https://modworkshop.net/mod/20654

**Crashlog**
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
        _create_statics_unit()  @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:647  
                 create_unit()  @mods/BeardLib-Editor/Hooks/WorldDefinition.lua:565  
                   SpawnUnit()  @mods/BeardLib-Editor/Classes/MapEditor.lua:409     
                all_ok_spawn()  @mods/BeardLib-Editor/Classes/Map/StaticEditor.lua:1492  
               SpawnCopyData()  @mods/BeardLib-Editor/Classes/Map/StaticEditor.lua:1526  
                 SpawnPrefab()  @mods/BeardLib-Editor/Classes/Map/StaticEditor.lua:1410  
                   _callback()  @mods/BeardLib-Editor/Classes/Map/WorldDataEditor.lua:682  
                       final()  @mods/BeardLib/Classes/UI/Dialogs/ListDialog.lua:181  
                 RunCallback()  @mods/BeardLib/Classes/UI/MenuUI/Item.lua:1224      
                MousePressed()  @mods/BeardLib/Classes/UI/MenuUI/Item.lua:1350      
                MousePressed()  @mods/BeardLib/Classes/UI/MenuUI/Item.lua:1376      
                 mouse_press()  @mods/BeardLib/Classes/UI/MenuUI/MenuUI.lua:484     
                                lib/managers/mousepointermanager.lua:345            

-------------------------------

System information:
	Application version : 1.103.7.
	CPU : Intel(R) Core(TM) i3-2120 CPU @ 3.30GHz (1 core); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce GT 730 / nvldumd.dll[27.21.14.6192]
	Language : english
	Memory :     8159MB 152KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Microsoft (Speakers (High Definition Audio Device))

**Comment by Luffyyy** [comment]
Sounds like a problem with loading units, this should be fixed when the new method of loading units (without using extract) releases
