### ISSUE TITLE
[Crash] selecting InstanceSetParams element on most recent commit causes a crash

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/BeardLib-Editor#577]
**To Reproduce**
Steps to reproduce the behavior: go into a vanilla heist (red2 for example) and try to select an instancesetparam element related to the objectives you should crash.

**Crashlog**
Application has crashed: C++ exception
...dLib-Editor-master/Classes/Map/Elements/coreinstance.lua:46: attempt to call method 'get_link_color' (a nil value)

SCRIPT STACK

update() @mods/BeardLib-Editor-master/Classes/Map/Elements/coreinstance.lua:142
update() @mods/BeardLib-Editor-master/Classes/Map/MissionEditor.lua:185
update() @mods/BeardLib-Editor-master/Classes/MapEditor.lua:700
func() @mods/BeardLib-Editor-master/Core.lua:471
Call() @mods/base/req/core/Hooks.lua:109
original() @mods/base/lua/GameSetup.lua:6
update() @mods/base/req/core/Hooks.lua:265
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:557

**Comment by Whurrhurr** [comment]
still happens even after downloading commit 7e90647.

Application has crashed: C++ exception
...dLib-Editor-master/Classes/Map/Elements/coreinstance.lua:46: attempt to call method 'mission_element' (a nil value)

SCRIPT STACK

update() @mods/BeardLib-Editor-master/Classes/Map/Elements/coreinstance.lua:142
update() @mods/BeardLib-Editor-master/Classes/Map/MissionEditor.lua:185
update() @mods/BeardLib-Editor-master/Classes/MapEditor.lua:700
func() @mods/BeardLib-Editor-master/Core.lua:473
Call() @mods/base/req/core/Hooks.lua:109
original() @mods/base/lua/GameSetup.lua:6
update() @mods/base/req/core/Hooks.lua:265
update() lib/setups/networkgamesetup.lua:21
core/lib/setups/coresetup.lua:557

**Comment by Luffyyy** [comment]
FIxed
