### ISSUE TITLE
Crash when opening any map in the editor

### ISSUE THREAD

**Issue by rockymoto517** [Luffyyy/BeardLib-Editor#578]
C++ exception as the title says. I tried removing all my mods and trying but it didn't work.

crash:
[crash.txt](https://github.com/Luffyyy/BeardLib-Editor/files/6386772/crash.txt)

log:
[2021_04_27_log.txt](https://github.com/Luffyyy/BeardLib-Editor/files/6386770/2021_04_27_log.txt)

**Comment by Luffyyy** [comment]
Your beardlib is outdated that's my first assumption.

**Comment by rockymoto517** [comment]
I did have it updated but I deleted my beardlib files and installed it again just in case, still getting the same crash.

**Comment by Luffyyy** [comment]
Did you install it through github? Did you make sure that you don't have it installed twice? This crash was solved at least 3 times just by updating beardlib

**Comment by rockymoto517** [comment]
The zip file says the folder was last modified on 4/24 at 4:02, but I'll give it another shot still.

**Comment by rockymoto517** [comment]
It crashes specifically here if it helps
![image](https://user-images.githubusercontent.com/74614475/116312394-ff38fd00-a771-11eb-9dd0-4ffabc8b7859.png)

**Comment by Luffyyy** [comment]
I fixed some error, not sure if that'll help: https://github.com/simon-wh/PAYDAY-2-BeardLib

**Comment by rockymoto517** [comment]
Yeah, fixing those errors stopped the crash from happening. Thanks a bunch
