### ISSUE TITLE
[Bug] Commit 1e83ef9 breaks Dome Occlusion, Cubemap and Cube Light generation.

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/BeardLib-Editor#580]
**Describe the bug**
title. the editor reloads when resolution is changed if you have `    Hooks:PostHook(MenuComponentManager, "resolution_changed", "reload_to_fix_res", ClassClbk(BLE, "MapEditorCodeReload"))
` in Core.lua. why this was added is beyond me since it seems you didn't test out if it'd break this sort of stuff.

**Comment by Luffyyy** [comment]
It was added for the purpose of updating the editor when resolution updates, as you know changing resolution broke the UI and selection. That being said, like many changes, it's difficult to tell if there's not gonna be some bug introduced unfortunately. But it should be fixed quite easily, I recommend temporarily removing the function manually until I fix it.

**Comment by Whurrhurr** [comment]
that's what i did, that's how i found out what was actually causing this.
