### ISSUE TITLE
Ability to delete all elements from the map without having to select them all.

### ISSUE THREAD

**Issue by CoolDude034** [Luffyyy/BeardLib-Editor#582]
**Is your feature request related to a problem? Please describe.**
Its currently hard to remove elements without having to select all elements and having to wait 9999 years for payday to load again, i rather have a way to delete all of the existing elements of the map at once.

**Describe the solution you'd like**
I want an option which i can press that automatically deletes all current elements from the map, would be useful for if i want to use a vanilla heist as a base but dont want its scripted stuff.

**Describe alternatives you've considered**
There is none, tho currently you can remove elements by selecting every element but this takes bit long on big maps.

**Additional context**
A small button to quickly remove all elements from the map would be nice.

**Comment by Makowo** [comment]
You can already do this by clicking the trash can icon next to the script

![payday2_win32_release_WLaYY02OgB](https://user-images.githubusercontent.com/13400548/118927860-0635d400-b908-11eb-8608-cc8558a6190d.png)
