### ISSUE TITLE
payday 2 crashes whem loading any level in beardlib editor

### ISSUE THREAD

**Issue by waxer-br** [Luffyyy/BeardLib-Editor#587]
game crashes whem attempting to load a beardlib editor level

game crashes after 6 to 10 seconds on the loading screen of whem you select to edit a level , it's as easy as that for it to crash

[crash log.txt](https://github.com/Luffyyy/BeardLib-Editor/files/6642901/crash.log.txt)

**Comment by waxer-br** [comment]
hello?

**Comment by waxer-br** [comment]
[world cameras.txt](https://github.com/Luffyyy/BeardLib-Editor/files/6696769/world.cameras.txt)
more info i guess

**Comment by Luffyyy** [comment]
Are you sure this happens in any level? It works fine for other people and for me.
