### ISSUE TITLE
Trying to use environment loaded by DB crashes.

### ISSUE THREAD

**Issue by MiamiCenterPL** [Luffyyy/BeardLib-Editor#595]
**Describe the crash**
Environment menu is crashing when trying to use environment loaded by DB
I tried using; environments/pd2_mex_environments/pd2_env_mex_sunset

**To Reproduce**
Load environment with DB and try to use it.

**Crashlog**
Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 

-------------------------------

Current thread: Main
Script stack:
                 script_data()  @mods/PAYDAY-2-BeardLib-master/Classes/Managers/FileManager.lua:33  
                       _load()  core/lib/managers/viewport/environment/coreenvironmentmanager.lua:262  
                   _get_data()  core/lib/managers/viewport/environment/coreenvironmentmanager.lua:233  
             set_environment()  core/lib/managers/viewport/environment/coreenvironmenthandler.lua:60  
on_default_environment_changed()  core/lib/managers/viewport/environment/coreenvironmenthandler.lua:308  
on_default_environment_changed()  core/lib/managers/viewport/corescriptviewport.lua:97  
     set_default_environment()  core/lib/managers/viewport/coreviewportmanager.lua:195  
                       final()  @mods/BeardLib-Editor-dev/Classes/Map/EnvironmentLayerEditor.lua:449  
                 RunCallback()  @mods/PAYDAY-2-BeardLib-master/Classes/UI/MenuUI/Item.lua:1224  
                    SetValue()  @mods/BeardLib-Editor-dev/Classes/MenuUIExt.lua:273  
                   _callback()  @mods/BeardLib-Editor-dev/Classes/MenuUIExt.lua:263  
                       final()  @mods/PAYDAY-2-BeardLib-master/Classes/UI/Dialogs/ListDialog.lua:181  
                 RunCallback()  @mods/PAYDAY-2-BeardLib-master/Classes/UI/MenuUI/Item.lua:1224  
                MousePressed()  @mods/PAYDAY-2-BeardLib-master/Classes/UI/MenuUI/Item.lua:1350  
                MousePressed()  @mods/PAYDAY-2-BeardLib-master/Classes/UI/MenuUI/Item.lua:1376  
                 mouse_press()  @mods/PAYDAY-2-BeardLib-master/Classes/UI/MenuUI/MenuUI.lua:484  
                                lib/managers/mousepointermanager.lua:345            

-------------------------------

**Comment by Luffyyy** [comment]
Will be fixed by BeardLib when loading the environment when needed.
