### ISSUE TITLE
[DEV] Copying instances is crashing.

### ISSUE THREAD

**Issue by MiamiCenterPL** [Luffyyy/BeardLib-Editor#603]
**Describe the crash**
Trying to clone instance is crashing with the latest dev version commit.

**To Reproduce**
Go to Project Manager, edit any project and try to clone vanilla instance.

**Crashlog**

Application has crashed: C++ exception
[string "core/lib/utils/coretable.lua"]:175: bad argument #1 to 'pairs' (table expected, got nil)

SCRIPT STACK

contains() core/lib/utils/coretable.lua:175
extra_package() @mods/BeardLib-Editor-dev/Classes/Project/ProjectLevelEditor.lua:168
clone_level() @mods/BeardLib-Editor-dev/Classes/Project/ProjectLevelEditor.lua:193
clbk() @mods/BeardLib-Editor-dev/Classes/Project/ProjectInstanceEditor.lua:62
run_callback() @mods/PAYDAY-2-BeardLib-master/Classes/UI/Dialogs/InputDialog.lua:53
final() @mods/PAYDAY-2-BeardLib-master/Classes/UI/Dialogs/MenuDialog.lua:182
RunCallback() @mods/PAYDAY-2-BeardLib-master/Classes/UI/MenuUI/Item.lua:1224
MousePressed() @mods/PAYDAY-2-BeardLib-master/Classes/UI/MenuUI/Item.lua:1350
MousePressed() @mods/PAYDAY-2-BeardLib-master/Classes/UI/MenuUI/Item.lua:1376
mouse_press() @mods/PAYDAY-2-BeardLib-master/Classes/UI/MenuUI/MenuUI.lua:484
lib/managers/mousepointermanager.lua:345

-------------------------------

**Comment by Luffyyy** [comment]
Make sure also that BeardLib is updated as I had to fix something there too
