### ISSUE TITLE
[DEV] Loading scenes from DB doesn't work

### ISSUE THREAD

**Issue by MiamiCenterPL** [Luffyyy/BeardLib-Editor#604]
**Describe the bug**
I am trying to load `core/environments/skies/sky_1313_cloudy_dark/sky_1313_cloudy_dark` from DB, but whenever I click the path nothing happens.
In console I found this error;
`04:08:41 PM Lua: [BeardLib-Editor] Extension core/environments/skies/sky_1313_cloudy_dark/sky_1313_cloudy_dark does not have a read function!`

**To Reproduce**
Try to load this from DB.

**Comment by Luffyyy** [comment]
I wouldn't recommend using scenes for now. I'm still trying to fix #595.
