### ISSUE TITLE
NO interaction tweak data ID set.

### ISSUE THREAD

**Issue by zddcommm231** [Luffyyy/BeardLib-Editor#608]
When I use interaction, there are only two available interactions in the tweet data list.
And show：
NO interaction tweak data ID set.
the element will not work.
![1](https://user-images.githubusercontent.com/73471643/124258716-4c659080-db60-11eb-83b2-d95a45813cbe.png)

**Comment by Luffyyy** [comment]
This just takes the tweakdata directly, it cannot really fail unless some map touches tweak_data.interaction and messes it up.
