### ISSUE TITLE
Game crashes when you click Browse units on SpawnEnemyDummy

### ISSUE THREAD

**Issue by CoolDude034** [Luffyyy/BeardLib-Editor#625]
**Describe the bug**
When you spawn SpawnEnemyDummy and click on Browse units, the game crashes.

**To Reproduce**
Step 1: Create a SpawnEnemyDummy
Step 2: Click on browse units
Step 3: if lucky, you will get browse units window, else you crash. Only way to bypass is changing enemy unit types by script, which isn't ideal.

**Comment by Luffyyy** [comment]
Should be fixed in dev branch, should be released in a few days.

**Comment by CoolDude034** [comment]
> Should be fixed in dev branch, should be released in a few days.

alright thanks, i wait then
