### ISSUE TITLE
Select/Deselect windows have small misclick border

### ISSUE THREAD

**Issue by RexTheWho** [Luffyyy/BeardLib-Editor#628]
There's a small gap that is surprisingly easy to misspress when dealing with lots of items.
Mouse pointer looks like its over the dropdown but is actually about to remove the item from the list.

![image](https://user-images.githubusercontent.com/26837908/125549733-9bf8290e-eca0-405b-bdb2-859b19b06250.png)

~~I have been accidentally pressing this all morning~~

**Comment by Luffyyy** [comment]
Modified the arrows too.
