### ISSUE TITLE
Objective with amount and state complete not working

### ISSUE THREAD

**Issue by MathiasAC** [Luffyyy/BeardLib-Editor#642]
When I add an objective element with an amount and using the state complete it doesn't activate.

In the second picture,
I have walked into an area trigger and it activates a waypoint and the objective but the objective doesn't change
if I choose a different state then it works but the amount isn't used

![1](https://user-images.githubusercontent.com/25396967/127754852-ccb4a5cf-8da3-4174-ac5b-dbf56f2ad41a.jpg)
![2](https://user-images.githubusercontent.com/25396967/127754853-83ce7656-8727-4c1b-be9f-a573cddb904a.jpg)
![3](https://user-images.githubusercontent.com/25396967/127754918-3057eb78-8560-40fa-bc92-e13aa9721477.jpg)

**Comment by RexTheWho** [comment]
Complete [objective_id] will only complete objectives that have that [objective_id] ID.
In your case you are using the wrong objective to complete I assume since your current one shown is obj_first.
The game technically supports multiple active objectives so this is an intended feature.

**Comment by MathiasAC** [comment]
oh was following a youtube video by Lulsfurcupcake must have made a mistake
anyway thank you, it helped

**Comment by MiamiCenterPL** [comment]
When making objectives with Amount I Highly suggest using obj_link instance, it is used in First World Bank for example.
With it you can count objectives value even before you start the objective itself. You can configure this instance with InstanceParams element, and Instance Input/Output Event, it's really easy to understand how it works, and it does speed up development
