### ISSUE TITLE
cloning instances crash

### ISSUE THREAD

**Issue by sooooosh** [Luffyyy/BeardLib-Editor#643]
**Describe the crash**
after typing in a name for the cloned instance, the game crashes.
(Yes, SBLT, BeardLib and BLE are updated.)

**To Reproduce**
- Open any project,
- Click on 'Clone Instance',
- Select any Instance,
- Type in any name,
- *Game dies*

**Crashlog**
Application has crashed: C++ exception
...-Editor-master/Classes/Project/ProjectInstanceEditor.lua:45: attempt to index field '_mod' (a nil value)

SCRIPT STACK

final() @mods/PAYDAY-2-BeardLib-master/Classes/UI/Dialogs/InputDialog.lua:62
RunCallback() @mods/PAYDAY-2-BeardLib-master/Classes/UI/MenuUI/Item.lua:1291
MousePressed() @mods/PAYDAY-2-BeardLib-master/Classes/UI/MenuUI/Item.lua:1422
MousePressed() @mods/PAYDAY-2-BeardLib-master/Classes/UI/MenuUI/Item.lua:1448
mouse_press() @mods/PAYDAY-2-BeardLib-master/Classes/UI/MenuUI/MenuUI.lua:511
lib/managers/mousepointermanager.lua:345

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        
                         ntdll  (???)     RtlAllocateHeap                                     

-------------------------------

Current thread: Main

-------------------------------

**Comment by MiamiCenterPL** [comment]
Same happens when trying to create a completely new instance.
*same crash.txt too*
