### ISSUE TITLE
Some elements are not saved properly when map backups are enabled

### ISSUE THREAD

**Issue by segabl** [Luffyyy/BeardLib-Editor#682]
### Describe the bug

When changing toggle menu items on elements, there's a chance they won't save properly when a backup of the map you are editing exists. After deleting the backup folder, reloading the map, making the changes and saving it, the changes properly applied after another reload.

### Steps to reproduce the issue

Enable map backups, open a map and change some stuff, save and reload, basically make sure a backup is created. Afterwards edit the map again and disable a toggle item (in my case it was access flags of a special objective/prefered groups in a spawn group). saving and reloading the heist has a big chance of reverting the changes just done.

### Minimal reproduction

[Old Safehouse Raid.zip](https://github.com/Luffyyy/BeardLib-Editor/files/7447740/Old.Safehouse.Raid.zip)

Happened here when editing the 2 nav links in front of the windows

**Comment by Luffyyy** [comment]
Cannot get it to happen. Can someone else confirm?

**Comment by segabl** [comment]
might have been some weirdness on my end, I've edited those 2 elements so many times, and everytime I reopened the level later i found them to be reset. again, deleting the backups folder might have not done anything and I could have just gotten lucky and it saved that time
