### ISSUE TITLE
Saving doesn't work

### ISSUE THREAD

**Issue by giulgu17** [Luffyyy/BeardLib-Editor#683]
### Describe the bug

Basically if I try to save some changes to a map, it doesn't work.

### Steps to reproduce the issue

I know it's probably dont really know how to exactly describe it, I just simply try to edit a map and save it but it doesn't actually save.

### Log file

[2021_10_31_log.txt](https://github.com/Luffyyy/BeardLib-Editor/files/7448951/2021_10_31_log.txt)

**Comment by Luffyyy** [comment]
> 02:38:34 PM Lua: [BeardLib] [Map Framework] Could not read Maps/test/main.xml
Your map is most likely not setup correctly. There might be an error in the main.xml.
