### ISSUE TITLE
rotation gizmo can be selected and removed, causing crashes

### ISSUE THREAD

**Issue by sooooosh** [Luffyyy/BeardLib-Editor#691]
### Describe the bug

The rotation gizmo can be selected when using the right-click+drag multi selection. Doing this the gizmo can actually be deleted, which causes the game to crash when selecting anything after that, trying to disable it in the toolbar or pressing the rotation hotkey.

This does not happen with the move gizmo, it is completely ignored by the multi selection.

### Steps to reproduce the issue

- select any unit
- enable the rotation gizmo
- deselect
- use right-click + mouse drag over the just deselected unit, the rotation gizmo should now be selected
- delete the selection
- selecting anything or disabling the rotation gizmo will now crash the game

**Comment by Luffyyy** [comment]
Check if that does the trick.

**Comment by sooooosh** [comment]
nope, didn't fix it

https://user-images.githubusercontent.com/37846872/145842737-ced4e66a-2904-44a7-a17c-3668bc12a03d.mp4
