### ISSUE TITLE
the game crashes

### ISSUE THREAD

**Issue by kaloyan132** [Luffyyy/BeardLib-Editor#694]
### Describe the crash

i tried cloning a map (alaskan deal) but when trying to load in it crashes the game freezes and if i ctrl alt del it crashes fully
tried with a new map same thing i waited for 10 mins it didnt load

### Steps to reproduce the crash

trying to edit any map

### Logs

[2021_12_27_log.txt](https://github.com/Luffyyy/BeardLib-Editor/files/7777681/2021_12_27_log.txt)

**Comment by MiamiCenterPL** [comment]
Can you include also crash report? You can find it at %localappdata%/PAYDAY 2/crash.txt

One other advice from me is changing your Streaming Chunks settings to a higher value (like arround 2000). You can find that in Advanced Video options.

**Comment by kaloyan132** [comment]
[crashlog.txt](https://github.com/Luffyyy/BeardLib-Editor/files/7779711/crashlog.txt)

**Comment by kaloyan132** [comment]
i didnt extract the files with the script i just clicked extract all on DBV and extracted them in a new folder in mod overrides
i installed runtime 3 and 5

**Comment by MiamiCenterPL** [comment]
It seems like Full Speed Swarm is causing these crashes, try removing it, and increasing Streaming Chunks.

**Comment by kaloyan132** [comment]
can i just disable it from the mod setting without physically moving it

**Comment by MiamiCenterPL** [comment]
It's safer to move it physically, and fully restart the game.

**Comment by kaloyan132** [comment]
i disbled it from the mod menu and it worked thx next time i will know to look at the right crashlog XD
can i make it so i look around with right click instead of shift

**Comment by MiamiCenterPL** [comment]
I have never changed the looking key, but try in keybind settings in BeardLib Editor.
@Luffyyy you can close it now.

**Comment by Luffyyy** [comment]
> i disbled it from the mod menu and it worked thx next time i will know to look at the right crashlog XD
> can i make it so i look around with right click instead of shift
> 

No. Holding right click let's you select multiple selections at once.
