### ISSUE TITLE
Can't edit custom levels / BLE doesn't support proton

### ISSUE THREAD

**Issue by rlenhub** [Luffyyy/BeardLib-Editor#698]
### Describe the bug

Projects work fine. In my project screen, the level(s) appear. However, none of them show up in the BLE Levels screen. Oddly enough, I experienced this bug the first time I used the editor. I originally fixed this through a few restarts. This time, I haven't been so lucky.

### Steps to reproduce the issue

1. Run Payday 2 in Linux through Proton
2. Open the BeardLib Editor and create a new project
3. Create a new level
4. Experience the emptiness of the Levels screen

**Comment by rlenhub** [comment]
UPDATE: I found a button on the main menu. Clicking it revealed an interesting popup pictured below.
![Screenshot_20220106_064823](https://user-images.githubusercontent.com/33167901/148385502-99dbf2cc-7af2-4721-be18-5452392a5c6f.png)

**Comment by Luffyyy** [comment]
Unfortunately the editor works only for Windows. Since it does additional things, it's unlikely it'll work even on proton.

**Comment by rlenhub** [comment]
> Unfortunately the editor works only for Windows. Since it does additional things, it's unlikely it'll work even on proton. 

What I found odd was that it worked at all. I made some decent progress for a while but then it just stopped working. Could have been caused by a computer restart. Anyways, thanks for the input.
