### ISSUE TITLE
Editor not loading units when adding from DB

### ISSUE THREAD

**Issue by AkinariHex** [Luffyyy/BeardLib-Editor#727]
### Describe the bug

I made a reset of my `level/add.xml` and loaded all the assets from DB but when testing the map I noticed that only the host could see the guards and civilians.

Heading to the `add.xml` file I noticed that `load="true"` was missing for all the units so I fixed them manually.

Loading by DB:
![Before fixing](https://akinariosu.s-ul.eu/fSrbNvKN)

After fixing:
![After fixing](https://akinariosu.s-ul.eu/25rmC50r)

### Steps to reproduce the issue

Just delete all the content of `add.xml` file into your level folder, open the editor, and load all the assets from DB.

**Comment by Luffyyy** [comment]
It's possible that the editor just doesn't add load=true for network units' base unit, this needs to be tested and in case it's required we'd just have to tell the code to do that (if there's a husk).

**Comment by Xeletron** [comment]
Fixed in a95d9fffd6f4b6122b1e73def93e5b65551ddc33
