### ISSUE TITLE
Loading assets from DB should not include animation states

### ISSUE THREAD

**Issue by segabl** [Luffyyy/BeardLib-Editor#728]
### Describe the bug

When loading units from DB, the editor goes through all the unit dependencies and adds them aswell. However, this causes issues with SuperBLTs XML tweaker as it adds files that have already been loaded by the game. Specifically, animation definitions and animation state files do not have to be included when loading a unit as they are already loaded by the base game.

### Steps to reproduce the issue

The issue can be reproduced by doing XML tweaks to the `anims/units/enemies/cop/std.animation_states` file and then loading a map that includes said file in its assets to load from DB, such as Proving Grounds. A wren error will occur, stating that said file has already been loaded.

**Comment by segabl** [comment]
This is actually a bigger issue of the editor loading units that are already available through the base package. Set the test unit of a SO to some specific base package enemy and the entire enemy will be added to the add.xml (which in this case is even worse since thats just a debugging option)

**Comment by Xeletron** [comment]
Added multiple options to combat this issue in a95d9fffd6f4b6122b1e73def93e5b65551ddc33
