### ISSUE TITLE
BeardLibEditor Menu doesn't appear in options

### ISSUE THREAD

**Issue by AtomykAU** [Luffyyy/BeardLib-Editor#730]
### Describe the bug

I've installed the newest SuperBLT and BeardLib, the neccessary .NET runtimes, and extracted bundle_db.blb. Not sure why it's not appearing in the menu, my menu attached:
![20220608154017_1](https://user-images.githubusercontent.com/107096921/172540261-2e69a097-18c2-4d87-b1a5-0a07cb9dd5a6.jpg)

### Steps to reproduce the issue

I have no fucking clue how this is happening or why

### Log file

[2022_06_08_log.txt](https://github.com/Luffyyy/BeardLib-Editor/files/8858549/2022_06_08_log.txt)

**Comment by TonisGaming** [comment]
Looks like you don't have the editor installed or you've overridden something you shouldn't have

**Comment by AtomykAU** [comment]
I'm retarded. I installed the editor but not BeardLib itself :/
