### ISSUE TITLE
[Loading from Database] Loading underlay scenes from the database does not actually load the underlay

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/BeardLib-Editor#737]
### Describe the bug

title. the underlay will show up in the underlay selection menu, but trying to select the underlay you loaded from database will cause a crash.

### Steps to reproduce the issue

load up any custom level in BLE, check what underlays are actually loaded so you don't try to load an already loaded underlay from DB and load the underlay through the database, now try to select it as your underlay and you will crash.

**Comment by Xeletron** [comment]
Looks like its one of those cases where it needs load = "true" to work correctly. Try adding it manually to the scene in the add.xml and see if it works like that. I'll try to make it add that by default

**Comment by Whurrhurr** [comment]
added load="true" to <scene path="core/environments/skies/sky_0200_night_moon_stars/sky_0200_night_moon_stars"/> and it works fine now.
