### ISSUE TITLE
Data files download doesn't work

### ISSUE THREAD

**Issue by TemApex** [Luffyyy/BeardLib-Editor#755]
### Describe the bug

When installing the editor it asks to download data files for the editor to work, clicking "yes" results in it getting stuck on "Waiting for a response" and it never downloads. I've tried redownloading BeardLib, redownloading SuperBLT, downloading the GitHub version of BeardLib instead of the ModWorkshop version, nothing works.
![image](https://user-images.githubusercontent.com/57864042/199572924-a0347cb5-6bc9-4bf0-bc83-b2c81e54e8ff.png)

### Steps to reproduce the issue

Download the editor and try to download the data files when prompted.

**Comment by Luffyyy** [comment]
Download them manually from modworkshop. Updates/in game downloads are not working right now
