### ISSUE TITLE
Player_Spawner crash

### ISSUE THREAD

**Issue by dyx695206669** [Luffyyy/BeardLib-Editor#756]
### Describe the crash

While I try to enter my level, it will crash after "hold enter to skip".

### Steps to reproduce the crash

At first, everything was right. Then I created a new plane, but my Player_ Spawner is too far from the plane, so I move it near the plane. Then I'm going to enter the map to see if it works, but it crashes.
play offline -->  contract_broker  -->  custom heist  -->  my level  -->  buy contract  -->  ready  -->  hold enter to skip  -->hold enter -->  crash

### Logs

Application has crashed: access violation

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                           ???  (???)     ???                                                 
                           ???  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main
Script stack:
                   post_init()  lib/units/beings/player/playermovement.lua:136      
                   post_init()  lib/units/beings/player/playerbase.lua:42           
                                lib/units/beings/player/playersound.lua:5           
                  spawn_unit()                                                      
                          =[C]  spawn_unit()                                        
                                lib/network/base/networkpeer.lua:2275               
               spawn_players()                                                      
lib/network/base/basenetworksession.lua:1513  update()                                            
                                lib/states/ingamewaitingforplayers.lua:300          
                      update()                                                      
core/lib/utils/game_state_machine/coregamestatemachine.lua:92  original()                                          
                                lib/setups/setup.lua:916                            
                      update()                                                      
@mods/base/req/core/Hooks.lua:288  original()                                          
                                lib/setups/gamesetup.lua:800                        
                      update()                                                      
@mods/base/req/core/Hooks.lua:288  update()                                            
                                lib/setups/networkgamesetup.lua:21                  
core/lib/setups/coresetup.lua:559  
-------------------------------

**Comment by Xeletron** [comment]
Do you have working navigation close to the player spawn? Even if its only you on the level the game still needs at least 1 nav segments on the level

**Comment by dyx695206669** [comment]
> Do you have working navigation close to the player spawn? Even if its only you on the level the game still needs at least 1 nav segments on the level

Ohhhh! It works! Thank you very much! It was that I forgot to build a new navigation in the new place...My mistakes, thanks again for your great help!
