### ISSUE TITLE
Element: AreaTrigger - Instigator Name cannot be removed once set

### ISSUE THREAD

**Issue by Whurrhurr** [Luffyyy/BeardLib-Editor#759]
### Describe the bug

Title. setting an equipment instigator in Instigator Name, you aren't allowed to remove what was picked because there's no option to have no equipment for an instigator name

![218620_20230106024901_1](https://user-images.githubusercontent.com/33162051/210997062-79dc4227-6896-4076-b93a-46c7ca3b8d9e.png)

### Steps to reproduce the issue

just set an instigator name to one of the options, you now have no way of removing it outside of manually editing the .mission file.

**Comment by Xeletron** [comment]
The Instigator Name parameter is only used if the instigator is set to 'equipment' which requires the instigator name, so I dont think reseting it would make much sense, do you have a special use case for it?
To clear up confusions in the future with this, I could make the Instigator Name option only visible if the instigator is set to equipment.

**Comment by Whurrhurr** [comment]
make it so that instigator name option is only visible if the instigator is set to equipment.
