### ISSUE TITLE
Brushes Don't Save

### ISSUE THREAD

**Issue by PocketWatchThee** [Luffyyy/BeardLib-Editor#772]
When I remove or add brushes to a map and hit the save button it tabs me out of the game. When I tab back into the game and save again, it doesn't tab me out again, but when I reload the map, all changes made to brushes are gone. This might just be an issue for me, I don't know.

**Comment by Xeletron** [comment]
You might be missing dotnet5.0.  https://dotnet.microsoft.com/download/dotnet/5.0/runtime
you'll need the 64bit desktop version

**Comment by PocketWatchThee** [comment]
Still tabs me out which is probably a separate issue, but it DOES save brushes now. Hugely appreciated!
