### ISSUE TITLE
The files don't download neither from git nor the "Data Files"

### ISSUE THREAD

**Issue by KovoranPlay** [Luffyyy/BeardLib-Editor#774]
I've just installed the BeardLib-editor since I've noticed that modworkshop.net is down, therefore there was no Stealthable Counterfeit available, so I've decided to change that. Found this editor, but the files aren't available for download due to U237 breaking the game entirely. Anyone can help me with the issue?
![image_2023-06-14_012522975](https://github.com/Luffyyy/BeardLib-Editor/assets/72622792/1e596d2a-f28d-4468-b4f2-16d263f18401)
Have been like that ever since I've installed the mod

**Comment by Xeletron** [comment]
It might have been the fault of modworkshop being down, do you have any more success now that the site is somewhat functional again?

**Comment by KovoranPlay** [comment]
Nah, Modworkshop is still downed. I guess until that the mod is kinda useless

**Comment by Luffyyy** [comment]
MWS is now working so closing
